import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { OperationalShell } from '@/components/application/operational-shell'
import { AppButton, PageHeading, SurfaceCard } from '@/components/application/visual'
import { Input } from '@/components/ui/input'
import { ErrorState, LoadingState } from '@/components/feedback/states'
import { apiErrorMessage } from '@/lib/api-error'
import { inventoryApi } from '../api/inventory.api'
import { useCategories, useInventoryCommand } from '../hooks/use-inventory'
import type { Category } from '../types'
const schema = z.object({ name: z.string().trim().min(1, 'Enter a category name.').max(100), is_active: z.boolean() })
type Values = z.infer<typeof schema>
function CategoryForm({ record, done }: { record?: Category; done: () => void }) { const key = useRef({ payload: '', key: crypto.randomUUID() }); const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { name: record?.name ?? '', is_active: record?.is_active ?? true } }); const command = useInventoryCommand<Values, Category>(v => { const payload = JSON.stringify(v); if (key.current.payload !== payload) key.current = { payload, key: crypto.randomUUID() }; return inventoryApi.category(record?.id, { ...v, expected_version: record?.version ?? 0 }, key.current.key) }); return <SurfaceCard className="management-card"><h2>{record ? 'Edit Category' : 'Add Category'}</h2>{command.error && <p role="alert" className="auth-error">{apiErrorMessage(command.error)}</p>}<form onSubmit={form.handleSubmit(async v => { if (command.isPending) return; try { await command.mutateAsync(v); form.reset(); done() } catch { form.setFocus('name') } })}><fieldset disabled={command.isPending}><div className="auth-field"><label htmlFor="category-name">Category name</label><Input id="category-name" {...form.register('name')} aria-invalid={!!form.formState.errors.name} />{form.formState.errors.name && <p role="alert" className="field-error">{form.formState.errors.name.message}</p>}</div><label className="inventory-checkbox"><input type="checkbox" {...form.register('is_active')} />Available for new equipment</label><p className="management-note">Existing equipment keeps its category when the category is made inactive.</p><AppButton type="submit">Save Category</AppButton></fieldset></form></SurfaceCard> }
export function CategoryManagement() { const [page, setPage] = useState(1), [editing, setEditing] = useState<Category | undefined>(), [revision, setRevision] = useState(0); const query = useCategories(page); return <OperationalShell active="Inventory"><PageHeading title="Equipment Categories" description="Manage FSMO catalog categories." /><Link to="/staff/inventory">← Back to inventory</Link><div className="management-detail-grid"><SurfaceCard className="management-card"><h2>Categories</h2>{query.isPending ? <LoadingState /> : query.isError ? <ErrorState description={apiErrorMessage(query.error)} /> : query.data.length === 0 ? <p>No categories yet.</p> : <ul className="management-audit">{query.data.map(c => <li key={c.id}><strong>{c.name}</strong><span>{c.is_active ? 'Active' : 'Inactive'}</span><AppButton variant="outline" onClick={() => { setEditing(c); setRevision(r => r + 1) }}>Edit</AppButton></li>)}</ul>}<div className="management-actions"><AppButton variant="outline" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous categories</AppButton><AppButton variant="outline" disabled={(query.data?.length ?? 0) < 100} onClick={() => setPage(p => p + 1)}>More categories</AppButton><AppButton onClick={() => { setEditing(undefined); setRevision(r => r + 1) }}>Add Category</AppButton></div></SurfaceCard><CategoryForm key={`${editing?.id ?? 'new'}-${revision}`} record={editing} done={() => { setEditing(undefined); setRevision(r => r + 1) }} /></div></OperationalShell> }
