import { useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useForm, useWatch } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Input } from '@/components/ui/input'
import { OperationalShell } from '@/components/application/operational-shell'
import { AppButton, PageHeading, SurfaceCard } from '@/components/application/visual'
import { ErrorState, LoadingState } from '@/components/feedback/states'
import { apiErrorMessage } from '@/lib/api-error'
import { inventoryApi } from '../api/inventory.api'
import { useCategories, useEquipmentDetail, useInventoryCommand } from '../hooks/use-inventory'
import { equipmentSchema, type EquipmentValues } from '../schemas/inventory.schema'
import type { Equipment } from '../types'
function Form({ record }: { record?: Equipment }) {
 const navigate = useNavigate(), [categoryPage, setCategoryPage] = useState(1), [categoryLabel, setCategoryLabel] = useState(record?.category_name ?? ''); const categories = useCategories(categoryPage); const key = useRef({ payload: '', key: crypto.randomUUID() })
 const form = useForm<EquipmentValues>({ resolver: zodResolver(equipmentSchema), defaultValues: { name: record?.name ?? '', description: record?.description ?? '', category_id: record?.category_id ?? '', opening_quantity: 0, reason: '' } })
 const selectedCategory=useWatch({control:form.control,name:'category_id'});const categoryField=form.register('category_id')
 const command = useInventoryCommand<EquipmentValues, Equipment>(async value => { const input = { name: value.name, description: value.description, category_id: value.category_id || null, expected_version: record?.metadata_version ?? 0 }; const payload = JSON.stringify({ ...input, ...(!record ? { opening_quantity: value.opening_quantity, reason: value.reason } : {}) }); if (key.current.payload !== payload) key.current = { payload, key: crypto.randomUUID() }; return record ? inventoryApi.edit(record.id, input, key.current.key) : inventoryApi.create({ ...input, opening_quantity: value.opening_quantity, reason: value.reason }, key.current.key) })
 async function submit(value: EquipmentValues) { if (command.isPending) return; try { const v = await command.mutateAsync(value); navigate(`/staff/inventory/${v.id}`, { replace: true }) } catch { form.setFocus('name') } }
 return <SurfaceCard className="management-card management-form"><Link to={record ? `/staff/inventory/${record.id}` : '/staff/inventory'}>← Back to inventory</Link><h2>Equipment information</h2>{command.error && <p role="alert" className="auth-error">{apiErrorMessage(command.error)}</p>}<form onSubmit={form.handleSubmit(submit)} noValidate><fieldset disabled={command.isPending}><div className="auth-field"><label htmlFor="equipment-name">Name</label><Input id="equipment-name" {...form.register('name')} aria-invalid={!!form.formState.errors.name} />{form.formState.errors.name && <p role="alert" className="field-error">{form.formState.errors.name.message}</p>}</div><div className="auth-field"><label htmlFor="equipment-description">Description</label><textarea id="equipment-description" {...form.register('description')} maxLength={2000} /></div><div className="auth-field"><label htmlFor="equipment-category">Category (optional)</label><select id="equipment-category" {...categoryField} onChange={e=>{void categoryField.onChange(e);setCategoryLabel(e.target.selectedOptions[0]?.textContent ?? '')}}><option value="">Uncategorized</option>{selectedCategory && !categories.data?.some(c => c.id === selectedCategory) && <option value={selectedCategory}>{categoryLabel}</option>}{categories.data?.filter(c => c.is_active || c.id === record?.category_id).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{(categories.data?.length === 100 || categoryPage > 1) && <div className="management-actions"><AppButton type="button" variant="outline" disabled={categoryPage === 1} onClick={() => setCategoryPage(p => p - 1)}>Previous categories</AppButton><AppButton type="button" variant="outline" disabled={(categories.data?.length ?? 0) < 100} onClick={() => setCategoryPage(p => p + 1)}>More categories</AppButton></div>}{!record && <><div className="auth-field"><label htmlFor="equipment-opening">Opening available quantity</label><Input id="equipment-opening" type="number" min={0} max={2147483647} {...form.register('opening_quantity', { valueAsNumber: true })} aria-invalid={!!form.formState.errors.opening_quantity} />{form.formState.errors.opening_quantity && <p role="alert" className="field-error">{form.formState.errors.opening_quantity.message}</p>}</div><div className="auth-field"><label htmlFor="equipment-reason">Opening stock explanation</label><Input id="equipment-reason" {...form.register('reason')} aria-invalid={!!form.formState.errors.reason} />{form.formState.errors.reason && <p role="alert" className="field-error">{form.formState.errors.reason.message}</p>}</div></>}
 <p className="management-note">Stock changes are recorded separately in inventory history. Catalog images can be added from equipment details.</p><AppButton type="submit" disabled={command.isPending}>{command.isPending ? 'Saving…' : 'Save Equipment'}</AppButton></fieldset></form></SurfaceCard>
}
export function EquipmentForm() { const { id } = useParams(); const query = useEquipmentDetail(id ?? ''); return <OperationalShell active="Inventory"><PageHeading title={id ? 'Edit Equipment' : 'Add Equipment'} description="Maintain catalog metadata without rewriting physical stock." />{!id ? <Form /> : query.isPending ? <LoadingState /> : query.isError ? <ErrorState description={apiErrorMessage(query.error)} /> : <Form key={query.data.metadata_version} record={query.data} />}</OperationalShell> }
