import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Search, Check, Clock, Package, CircleAlert } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { OperationalShell } from '@/components/application/operational-shell'
import { BorrowerShell } from '@/components/application/shells'
import { borrowerDestinations } from '@/components/application/borrower-navigation'
import { AppButton, MetricCard, PageHeading, SurfaceCard, ThemeControl, ToneBadge } from '@/components/application/visual'
import { AvailabilityBadge } from '@/components/application/equipment'
import { EmptyState, ErrorState, LoadingState } from '@/components/feedback/states'
import { apiErrorMessage } from '@/lib/api-error'
import { useCategories, useEquipment } from '../hooks/use-inventory'
import { EquipmentImage } from './equipment-image'
export function EquipmentList({ borrower = false }: { borrower?: boolean }) {
 const [search, setSearch] = useState(''), [category, setCategory] = useState(''), [categoryLabel, setCategoryLabel] = useState(''), [status, setStatus] = useState(''), [available, setAvailable] = useState(false), [sort, setSort] = useState('name'), [page, setPage] = useState(1), [categoryPage, setCategoryPage] = useState(1)
 const categories = useCategories(categoryPage); const query = useEquipment({ page, per_page: 25, search, category_id: category || undefined, status: status || undefined, available_only: available, sort }); const data = query.data; const base = borrower ? '/borrower/equipment' : '/staff/inventory'
 const controls = <div className="management-toolbar inventory-toolbar"><label className="search-field"><Search size={18} aria-hidden="true" /><span className="sr-only">Search equipment</span><Input value={search} placeholder="Search equipment…" onChange={e => { setSearch(e.target.value); setPage(1) }} /></label><label>Category<select aria-label="Category" value={category} onChange={e => { setCategory(e.target.value); setCategoryLabel(e.target.selectedOptions[0]?.textContent ?? ''); setPage(1) }}><option value="">All categories</option>{category && !categories.data?.some(c=>c.id===category) && <option value={category}>{categoryLabel}</option>}{categories.data?.map(c => <option value={c.id} key={c.id}>{c.name}{!c.is_active ? ' (inactive)' : ''}</option>)}</select></label>{!borrower && <label>Status<select value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}><option value="">All statuses</option>{['ACTIVE', 'INACTIVE', 'ARCHIVED'].map(s => <option key={s}>{s}</option>)}</select></label>}<label>Sort<select value={sort} onChange={e => { setSort(e.target.value); setPage(1) }}><option value="name">Name</option><option value="available">Available quantity</option></select></label><label className="inventory-checkbox"><input type="checkbox" checked={available} onChange={e => { setAvailable(e.target.checked); setPage(1) }} />Available only</label></div>
 const body = <><PageHeading title={borrower ? 'Equipment Catalog' : 'Inventory'} description={borrower ? 'Browse FSMO equipment and current availability.' : 'Track available, reserved, checked-out and damaged physical stock.'} action={borrower ? <ThemeControl /> : <div className="management-actions"><AppButton nativeButton={false} render={<Link to="/staff/inventory/categories" />} variant="outline">Categories</AppButton><AppButton nativeButton={false} render={<Link to="/staff/inventory/new" />}>Add Equipment</AppButton></div>} />{controls}{(categories.data?.length === 100 || categoryPage > 1) && <div className="management-actions"><AppButton variant="outline" disabled={categoryPage === 1} onClick={() => setCategoryPage(p => p - 1)}>Previous categories</AppButton><AppButton variant="outline" disabled={(categories.data?.length ?? 0) < 100} onClick={() => setCategoryPage(p => p + 1)}>More categories</AppButton></div>}{categories.isError && <ErrorState description={apiErrorMessage(categories.error)} onRetry={() => { void categories.refetch() }} />}
 {!borrower && data && <div className="inventory-metrics">{([{ label: 'Available', value: data.totals.available, icon: Check }, { label: 'Reserved', value: data.totals.reserved, icon: Clock }, { label: 'Checked out', value: data.totals.checked_out, icon: Package }, { label: 'Damaged held', value: data.totals.damaged_held, icon: CircleAlert }]).map(m => <MetricCard key={m.label} {...m} />)}</div>}
 {query.isPending ? <LoadingState label="Loading equipment…" /> : query.isError ? <ErrorState description={apiErrorMessage(query.error)} onRetry={() => { void query.refetch() }} /> : !data?.items.length ? <SurfaceCard className="management-card"><EmptyState title={search || category || status || available ? 'No equipment matches' : 'No equipment yet'} description={borrower ? 'Contact FSMO for assistance.' : 'Add equipment to begin a traceable inventory.'} /></SurfaceCard> : borrower ? <div className="inventory-catalog">{data.items.map(v => <SurfaceCard className="equipment-card inventory-catalog-card" key={v.id}><EquipmentImage record={v} /><div className="equipment-copy"><h2>{v.name}</h2><p>{v.category_name || 'Uncategorized'}</p><p className="inventory-description">{v.description}</p></div><div className="equipment-controls"><AvailabilityBadge available={v.stock.available} state={v.stock.available > 0 ? 'available' : 'unavailable'} /><AppButton variant="outline" nativeButton={false} render={<Link to={`${base}/${v.id}`} />}>View Details</AppButton></div></SurfaceCard>)}</div> : <SurfaceCard className="management-card"><h2>Equipment inventory</h2><div className="data-table-shell"><div className="table-scroll"><table className="management-table"><thead><tr>{['Item', 'Category', 'Available', 'Reserved', 'Checked out', 'Damaged held', 'Status', 'Action'].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{data.items.map(v => <tr key={v.id}><td><strong>{v.name}</strong></td><td>{v.category_name || 'Uncategorized'}</td><td>{v.stock.available}</td><td>{v.stock.reserved}</td><td>{v.stock.checked_out}</td><td>{v.stock.damaged_held}</td><td><ToneBadge tone={v.status === 'ACTIVE' ? 'success' : 'neutral'}>{v.status}</ToneBadge></td><td><AppButton variant="outline" nativeButton={false} render={<Link to={`${base}/${v.id}`} />}>Open</AppButton></td></tr>)}</tbody></table></div></div></SurfaceCard>}
 {data && <div className="management-actions inventory-pagination"><p role="status">{data.total} equipment types · Page {page}</p><AppButton variant="outline" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</AppButton><AppButton variant="outline" disabled={page * 25 >= data.total} onClick={() => setPage(p => p + 1)}>Next</AppButton></div>}</>
 return borrower ? <BorrowerShell active="Equipment" destinations={borrowerDestinations}>{body}</BorrowerShell> : <OperationalShell active="Inventory">{body}</OperationalShell>
}
export function BorrowerCatalog() { return <EquipmentList borrower /> }
