import { useState } from 'react'
import { Link, useParams, useLocation } from 'react-router-dom'
import { BorrowerShell } from '@/components/application/shells'
import { borrowerDestinations } from '@/components/application/borrower-navigation'
import { AppButton, ThemeControl, ToneBadge } from '@/components/application/visual'
import { ManagementPage, ManagementCard, Notice, FormActions } from '@/components/application/management'
import { DirectoryTableRegion } from '@/components/application/directory'
import { ServerPagination } from '@/components/application/server-pagination'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { useDirectoryState } from '@/hooks/use-directory-state'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { ErrorState, LoadingState } from '@/components/feedback/states'
import { apiErrorMessage } from '@/lib/api-error'
import { useAuthStore } from '@/stores/auth-store'
import { inventoryApi } from '../api/inventory.api'
import { useEquipmentDetail, useInventoryCommand, useMovements } from '../hooks/use-inventory'
import { EquipmentImage } from './equipment-image'
import type { Equipment } from '../types'
function Detail({ record, borrower }: { record: Equipment; borrower: boolean }) {
 const role = useAuthStore(s => s.user?.role), view=useDirectoryState(), page=view.page('movement_page')
 const [review, setReview] = useState<{ record: Equipment; status: string; key: string } | null>(null)
 const location = useLocation(), history = useMovements(record.id, page)
 const status = useInventoryCommand<{ record: Equipment; status: string; key: string }, Equipment>(v => inventoryApi.status(v.record, v.status, v.key))
 const notice=(location.state as { stockNotice?: string } | null)?.stockNotice
 return <>{notice && <Notice tone="success">{notice}</Notice>}<div className="management-columns"><ManagementCard title={record.name} className="inventory-detail-image"><EquipmentImage record={record} /><dl className="management-dl"><dt>Category</dt><dd>{record.category_name || 'Uncategorized'}</dd><dt>Status</dt><dd><ToneBadge tone={record.status === 'ACTIVE' ? 'success' : 'neutral'}>{record.status}</ToneBadge></dd><dt>Description</dt><dd>{record.description || 'No description'}</dd>{!borrower && <><dt>Latest update</dt><dd>{new Date(record.updated_at).toLocaleString()}</dd></>}</dl>
 {borrower && <AppButton disabled={record.stock.available<=0} nativeButton={false} render={<Link to={`/borrower/borrowings/new?equipment_id=${record.id}`} />}>Request Equipment</AppButton>}
 {!borrower && record.status !== 'ARCHIVED' && <><FormActions><AppButton variant="outline" nativeButton={false} render={<Link to={`/staff/inventory/${record.id}/edit`} />}>Edit Equipment</AppButton><AppButton nativeButton={false} render={<Link to={`/staff/inventory/${record.id}/adjust`} />}>Stock Adjustment</AppButton>{role === 'ADMIN' && <AppButton variant="outline" nativeButton={false} render={<Link to={`/admin/inventory/${record.id}/reconcile`} />}>Reconcile Inventory</AppButton>}</FormActions><FormActions><AppButton variant="outline" onClick={() => setReview({ record, status: record.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE', key: crypto.randomUUID() })}>{record.status === 'ACTIVE' ? 'Make Inactive' : 'Make Active'}</AppButton><AppButton variant="outline" disabled={record.stock.reserved > 0 || record.stock.checked_out > 0 || !['NOT_INSTALLED','CLEAR'].includes(record.archive_safety??'')} onClick={() => setReview({ record, status: 'ARCHIVED', key: crypto.randomUUID() })}>Archive Equipment</AppButton></FormActions><p className="management-note">Manage the catalog image in Edit Equipment. Archive remains subject to custody and obligation checks.</p></>}
 </ManagementCard><ManagementCard title={borrower ? 'Current availability' : 'Current physical stock'}>{borrower ? <p className="inventory-available"><strong>{record.stock.available}</strong> available</p> : <dl className="stock-metrics">{[['Available', record.stock.available], ['Reserved', record.stock.reserved], ['Checked out', record.stock.checked_out], ['Damaged held', record.stock.damaged_held], ['Total tracked', record.stock.total_tracked]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}{!borrower && <Notice>These counts describe physical stock. Replacement accountability is not available yet; contact FSMO to resolve equipment obligations.</Notice>}</ManagementCard></div>
 {!borrower && <ManagementCard title="Inventory movement history" description="Recorded physical stock changes and their explanations.">{history.isPending ? <LoadingState /> : history.isError ? <ErrorState description={apiErrorMessage(history.error)} onRetry={()=>{void history.refetch()}} /> : history.data.length === 0 ? <p>No stock movements recorded on this page.</p> : <DirectoryTableRegion label="Inventory movement history"><Table className="management-history-table"><TableHeader><TableRow>{['Time', 'Movement', 'Quantity effect', 'Actor / reason'].map(h => <TableHead key={h} scope="col">{h}</TableHead>)}</TableRow></TableHeader><TableBody>{history.data.map(m => <TableRow key={m.id}><TableCell>{new Date(m.created_at).toLocaleString()}</TableCell><TableCell>{m.kind}<span className="directory-secondary">Sequence {m.sequence}</span></TableCell><TableCell>Available {m.delta.available > 0 ? '+' : ''}{m.delta.available}<span className="directory-secondary">Total tracked {m.after.total_tracked}</span></TableCell><TableCell>{m.reason}<span className="directory-secondary">{m.actor_id??'System expiration'}</span></TableCell></TableRow>)}</TableBody></Table></DirectoryTableRegion>}{!history.isError && <ServerPagination label="Inventory movements" pageKey="movement_page" page={page} count={history.data?.length??0} hasNext={history.data?.length===25} pending={history.isFetching} onPage={p=>view.update({movement_page:String(p)},false)} />}</ManagementCard>}
 <AlertDialog open={!!review} onOpenChange={open => { if (!open && !status.isPending) setReview(null) }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{review?.status === 'ARCHIVED' ? 'Archive equipment?' : 'Change equipment status?'}</AlertDialogTitle><AlertDialogDescription>{review?.record.name} will become {review?.status}. Historical stock and records are preserved. Inactive or archived equipment is hidden from the Borrower catalog. Archive cannot proceed with reservations, custody or unresolved replacement obligations.</AlertDialogDescription></AlertDialogHeader>{status.error && <Notice tone="danger">{apiErrorMessage(status.error)}</Notice>}<AlertDialogFooter><AlertDialogCancel disabled={status.isPending}>Cancel</AlertDialogCancel><AlertDialogAction disabled={status.isPending} onClick={async () => { if (!review || status.isPending) return; try { await status.mutateAsync(review); setReview(null) } catch { /* Keep review visible. */ } }}>Confirm Status Change</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>
}
export function EquipmentDetail({ borrower = false }: { borrower?: boolean }) { const { id = '' } = useParams(); const query = useEquipmentDetail(id); const body = <ManagementPage title="Equipment Details" domain="Equipment management" description={borrower ? 'Equipment information and current availability.' : 'Physical inventory counts and traceable movements.'} actions={borrower ? <ThemeControl /> : undefined} back={{to:borrower?'/borrower/equipment':'/staff/inventory',label:borrower?'Back to catalog':'Back to inventory'}}>{query.isPending ? <LoadingState /> : query.isError ? <ErrorState description={apiErrorMessage(query.error)} /> : <Detail record={query.data} borrower={borrower} />}</ManagementPage>; return borrower ? <BorrowerShell active="Equipment" destinations={borrowerDestinations}>{body}</BorrowerShell> : body }
export function BorrowerEquipmentDetail() { return <EquipmentDetail borrower /> }
