import { useDeferredValue } from 'react'
import { Link } from 'react-router-dom'
import { Check, Clock, Package, CircleAlert, Plus, SlidersHorizontal, ArrowUpRight } from 'lucide-react'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { DirectoryHeader, DirectoryPanel, DirectorySearch, DirectorySelect, DirectoryTableRegion, DirectoryStat } from '@/components/application/directory'
import { ServerPagination } from '@/components/application/server-pagination'
import { AppButton, ToneBadge } from '@/components/application/visual'
import { useDirectoryState } from '@/hooks/use-directory-state'
import { apiErrorMessage } from '@/lib/api-error'
import { useCategories, useEquipment } from '../hooks/use-inventory'
import { EquipmentImage } from './equipment-image'

export function InventoryDirectory() {
  const { value, page, update } = useDirectoryState()
  const currentPage = page(), categoryPage = page('category_page'), search = value('search'), deferred = useDeferredValue(search)
  const category = value('category_id'), available = value('available_only') === 'true'
  const status = ['ACTIVE', 'INACTIVE', 'ARCHIVED'].includes(value('status')) ? value('status') : ''
  const sort = value('sort') === 'available' ? 'available' : 'name'
  const categories = useCategories(categoryPage)
  const query = useEquipment({ page: currentPage, per_page: 25, search: deferred, category_id: category || undefined, status: status || undefined, available_only: available, sort })
  const data = query.data, totals = query.isError ? undefined : data?.totals
  return <div className="directory-page"><DirectoryHeader title="Inventory" description="Equipment and physical stock across the FSMO workspace." actions={<><AppButton nativeButton={false} variant="outline" render={<Link to="/staff/inventory/categories" />}><SlidersHorizontal aria-hidden="true" />Categories</AppButton><AppButton nativeButton={false} render={<Link to="/staff/inventory/new" />}><Plus aria-hidden="true" />Add Equipment</AppButton></>} />
    <section aria-label="Stock in matching equipment"><div className="directory-stock-heading"><h2>Physical stock</h2><span>Across all matching equipment</span></div><div className="directory-stats"><DirectoryStat label="Available" value={totals?.available} icon={Check} tone="success" /><DirectoryStat label="Reserved" value={totals?.reserved} icon={Clock} tone="warning" /><DirectoryStat label="Checked out" value={totals?.checked_out} icon={Package} /><DirectoryStat label="Damaged held" value={totals?.damaged_held} icon={CircleAlert} tone="danger" /></div></section>
    <DirectoryPanel title="Equipment directory" summary={data && !query.isError ? `${data.total.toLocaleString()} matching equipment types` : 'Browse equipment and stock'} pending={query.isPending} error={query.isError ? apiErrorMessage(query.error) : undefined} empty={!data?.items.length} onRetry={() => { void query.refetch() }} toolbar={<><DirectorySearch label="Search equipment" placeholder="Search equipment names" value={search} onChange={e => update({ search: e.target.value }, true, true)} /><DirectorySelect label="Category" value={category} onChange={e => update({ category_id: e.target.value, category_label: e.target.selectedOptions[0]?.textContent ?? '' })}><option value="">All categories</option>{category && !categories.data?.some(c => c.id === category) && <option value={category}>{value('category_label') || 'Selected category'}</option>}{categories.data?.map(c => <option key={c.id} value={c.id}>{c.name}{!c.is_active ? ' (inactive)' : ''}</option>)}</DirectorySelect><DirectorySelect label="Status" value={status} onChange={e => update({ status: e.target.value })}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="ARCHIVED">Archived</option></DirectorySelect><DirectorySelect label="Sort" value={sort} onChange={e => update({ sort: e.target.value === 'name' ? '' : e.target.value })}><option value="name">Name</option><option value="available">Available quantity</option></DirectorySelect><label className="directory-availability"><input type="checkbox" checked={available} onChange={e => update({ available_only: e.target.checked ? 'true' : '' })} />Available for borrowing</label>{(search || category || status || available || sort !== 'name') && <AppButton variant="ghost" onClick={() => update({ search: '', category_id: '', category_label: '', status: '', available_only: '', sort: '' })}>Clear filters</AppButton>}{categories.isError && <div className="directory-filter-error" role="alert"><span>{apiErrorMessage(categories.error)}</span><AppButton variant="outline" onClick={() => { void categories.refetch() }}>Retry categories</AppButton></div>}{(categoryPage > 1 || categories.data?.length === 100) && <div className="directory-category-pages"><ServerPagination label="Categories" pageKey="category_page" page={categoryPage} count={categories.data?.length ?? 0} hasNext={categories.data?.length === 100} pending={categories.isFetching} onPage={p => update({ category_page: String(p) }, false)} /></div>}</>} footer={data && <ServerPagination label="Equipment" page={data.page} total={data.total} perPage={data.per_page} count={data.items.length} totalPages={Math.ceil(data.total / data.per_page)} pending={query.isFetching} onPage={p => update({ page: String(p) }, false)} />}>
      <DirectoryTableRegion label="Equipment inventory table"><Table className="directory-inventory-table"><colgroup><col style={{ width: '28%' }} />{Array.from({ length: 4 }, (_, i) => <col key={i} style={{ width: '12%' }} />)}<col style={{ width: '12%' }} /><col style={{ width: '12%' }} /></colgroup><TableHeader><TableRow><TableHead scope="col">Equipment / category</TableHead><TableHead scope="col" className="directory-number">Available</TableHead><TableHead scope="col" className="directory-number">Reserved</TableHead><TableHead scope="col" className="directory-number">Checked out</TableHead><TableHead scope="col" className="directory-number">Damaged held</TableHead><TableHead scope="col">Status</TableHead><TableHead scope="col"><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{data?.items.map(item => <TableRow key={item.id}><TableCell><div className="directory-equipment"><EquipmentImage record={item} compact /><div><Link className="directory-record-name" to={`/staff/inventory/${item.id}`}>{item.name}</Link><span>{item.category_name || 'Uncategorized'}</span></div></div></TableCell><TableCell className="directory-number directory-available-number">{item.stock.available}</TableCell><TableCell className="directory-number">{item.stock.reserved}</TableCell><TableCell className="directory-number">{item.stock.checked_out}</TableCell><TableCell className="directory-number">{item.stock.damaged_held}</TableCell><TableCell><ToneBadge tone={item.status === 'ACTIVE' ? 'success' : 'neutral'} icon={Check}>{item.status === 'ACTIVE' ? 'Active' : item.status === 'INACTIVE' ? 'Inactive' : 'Archived'}</ToneBadge></TableCell><TableCell><AppButton variant="ghost" nativeButton={false} render={<Link to={`/staff/inventory/${item.id}`} aria-label={`Open ${item.name}`} />}>Open<ArrowUpRight aria-hidden="true" /></AppButton></TableCell></TableRow>)}</TableBody></Table></DirectoryTableRegion>
    </DirectoryPanel>
  </div>
}
