import { ProfileAvatar } from '@/features/profile/components/profile-avatar'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import { useParams, useLocation } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog'
import { Input } from '@/components/ui/input'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { AppButton, ToneBadge } from '@/components/application/visual'
import { ManagementPage, ManagementCard, FormSection, FormField, FormActions, Notice } from '@/components/application/management'
import { DirectoryTableRegion } from '@/components/application/directory'
import { ServerPagination } from '@/components/application/server-pagination'
import { LoadingState } from '@/components/feedback/states'
import { useDirectoryState } from '@/hooks/use-directory-state'
import { useAuthStore } from '@/stores/auth-store'
import { apiErrorMessage } from '@/lib/api-error'
import { accountsApi } from '../api/accounts.api'
import { useAccount, useAccountAudit, useAccountCommand } from '../hooks/use-accounts'
import { activationLabel, deliveryLabel } from '../lib/account-status'
import type { AccountRecord } from '../types'
const profileSchema = z.object({ name: z.string().trim().min(1).max(100), course: z.string().max(128), contact_number: z.string().max(32) })
function ProfileForm({ account, onSaved }: { account: AccountRecord; onSaved: () => void }) {
 const form = useForm<z.infer<typeof profileSchema>>({ resolver: zodResolver(profileSchema), defaultValues: account }); const command = useAccountCommand((values: z.infer<typeof profileSchema>) => accountsApi.profile(account.id, { ...values, expected_updated_at: account.updated_at }, crypto.randomUUID()))
 return <ManagementCard title="Edit profile"><form noValidate onSubmit={form.handleSubmit(async values => { if(command.isPending)return;try { await command.mutateAsync(values);onSaved() } catch { form.setFocus('name') } })} aria-busy={command.isPending}>
 {command.error && <Notice tone="danger">{apiErrorMessage(command.error)}</Notice>}<FormSection title="Profile information" disabled={command.isPending}>{(['name', 'course', 'contact_number'] as const).filter(field => account.borrower_type || field === 'name').map(field => <FormField key={field} id={`profile-${field}`} required={field==='name'} label={field === 'name' ? 'Full name' : field === 'course' ? 'Course / program (optional)' : 'Contact number (optional)'} error={form.formState.errors[field]?.message}><Input {...form.register(field)} /></FormField>)}</FormSection><FormActions><AppButton disabled={command.isPending} type="submit">{command.isPending?'Saving…':'Save Profile'}</AppButton></FormActions></form></ManagementCard>
}
export function AccountDetail({ staff = false }: { staff?: boolean }) {
 const { id = '' } = useParams(); const admin = useAuthStore(s => s.user?.role === 'ADMIN'); const query = useAccount(id, staff); const view=useDirectoryState(),page=view.page('audit_page'); const audit = useAccountAudit(id, staff, page); const [confirm, setConfirm] = useState(false); const [notice, setNotice] = useState(''); const location = useLocation()
 const status = useAccountCommand((account: AccountRecord) => accountsApi.status(account, staff, crypto.randomUUID())); const resend = useAccountCommand(() => accountsApi.resend(id, staff, crypto.randomUUID()))
 const base = staff ? '/admin/administration/accounts' : '/staff/borrowers'; const account = query.data
 return <ManagementPage title={account?.name ?? 'Account Details'} description="Identity, status and account history." back={{to:base,label:`Back to ${staff?'accounts':'borrowers'}`}}>{query.isPending ? <LoadingState label="Loading account…" /> : query.isError ? <Notice tone="danger">{apiErrorMessage(query.error)}<AppButton variant="outline" onClick={()=>{void query.refetch()}}>Retry</AppButton></Notice> : account && <>
 {(location.state as { created?: boolean } | null)?.created && <Notice tone="success">Account created. The account holder must complete activation.</Notice>}{notice && <Notice>{notice}</Notice>}
 <div className="management-columns"><ManagementCard title="Account information"><ProfileAvatar id={account.id} name={account.name} className="profile-avatar-large" /><div className="management-status"><div><small>Administrative status</small><ToneBadge tone={account.is_active ? 'success' : 'neutral'}>{account.is_active ? 'Active' : 'Inactive'}</ToneBadge></div><div><small>Activation status</small><ToneBadge tone={account.activation_required ? 'warning' : 'neutral'}>{activationLabel(account.activation_required)}</ToneBadge></div></div>
 <dl className="management-information"><div className="information-wide"><dt>Email</dt><dd>{account.email}</dd></div><div><dt>{staff ? 'Role' : 'Borrower type'}</dt><dd>{staff ? account.role : account.borrower_type || 'Unclassified existing account'}</dd></div>{account.student_id && <div><dt>Student ID</dt><dd>{account.student_id}</dd></div>}{!staff && <><div><dt>Course / program</dt><dd>{account.course || 'Not provided'}</dd></div><div><dt>Contact number</dt><dd>{account.contact_number || 'Not provided'}</dd></div></>}<div className="information-wide"><dt>Activation email</dt><dd>{deliveryLabel(account.delivery_status)}</dd></div></dl>
 {account.is_active && account.activation_required && <Notice tone="warning">This account is administratively active, but cannot sign in until activation is completed.</Notice>}
 {admin && account.role !== 'ADMIN' && <FormActions><AppButton variant="outline" onClick={() => setConfirm(true)}>{account.is_active ? 'Deactivate Account' : 'Reactivate Account'}</AppButton>{account.is_active && account.activation_required && <AppButton disabled={resend.isPending} onClick={() => { void resend.mutateAsync(undefined).then(value => setNotice(deliveryLabel(value.delivery_status)), () => undefined) }}>{resend.isPending ? 'Submitting…' : 'Send Activation Link'}</AppButton>}</FormActions>}{(status.error || resend.error) && <Notice tone="danger">{apiErrorMessage(status.error ?? resend.error)}</Notice>}</ManagementCard>
 <ManagementCard title={staff ? 'Administrative authority' : 'Accountability overview'}>{staff ? <Notice>Staff account creation and status changes are Admin-only. Existing Admin accounts are read-only here.</Notice> : account.obligations.availability === 'UNAVAILABLE' ? <Notice title="Accountability unavailable">Borrowing, fines and replacement records are not available in this phase. Contact FSMO to review outstanding obligations.</Notice> : <dl className="management-information">{[['Pending requests',account.obligations.pending_requests],['Active borrowings',account.obligations.active_borrowings],['Overdue borrowings',account.obligations.overdue_borrowings],['Unreturned units',account.obligations.unreturned_units],['Replacement units',account.obligations.replacement_units],['Fine balance (minor units)',account.obligations.fine_minor]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'Unavailable'}</dd></div>)}</dl>}{account.obligations.availability==='PARTIAL'&&<Notice>Borrowing counts are available. Fine and replacement balances remain unavailable; review them separately with FSMO.</Notice>}<p className="management-note">Deactivation preserves history and outstanding obligations. FSMO resolves them separately.</p>{!staff && <div><h3>Borrowing history</h3><Link className="management-back" to={`/staff/requests?borrower_id=${account.id}`}>View borrowing history</Link></div>}</ManagementCard></div>
 {admin && !staff && <ProfileForm key={account.updated_at} account={account} onSaved={()=>setNotice('Profile updated.')} />}
 {admin && <ManagementCard title="Account audit history">{audit.isPending ? <LoadingState label="Loading audit history…" /> : audit.isError ? <Notice tone="danger">{apiErrorMessage(audit.error)}<AppButton variant="outline" onClick={()=>{void audit.refetch()}}>Retry audit</AppButton></Notice> : audit.data.length === 0 ? <p className="management-empty">No recorded management events.</p> : <DirectoryTableRegion label="Account audit history table"><Table><TableHeader><TableRow><TableHead scope="col">Action</TableHead><TableHead scope="col">Time</TableHead><TableHead scope="col">Actor</TableHead></TableRow></TableHeader><TableBody>{audit.data.map(event=><TableRow key={event.id}><TableCell>{event.action.replaceAll('_',' ').toLowerCase()}</TableCell><TableCell><time dateTime={event.occurred_at}>{new Date(event.occurred_at).toLocaleString()}</time></TableCell><TableCell>{event.actor_id}</TableCell></TableRow>)}</TableBody></Table></DirectoryTableRegion>}{!audit.isError && <ServerPagination label="Audit events" pageKey="audit_page" page={page} count={audit.data?.length??0} hasNext={audit.data?.length===25} pending={audit.isFetching} onPage={p=>view.update({audit_page:String(p)},false)} />}</ManagementCard>}
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{account.is_active ? 'Deactivate' : 'Reactivate'} {account.name}?</AlertDialogTitle><AlertDialogDescription>{account.is_active ? 'This account will lose access. Outstanding fines, active or overdue borrowings, unreturned equipment and replacement obligations will remain unchanged. These obligations do not block authorized deactivation. Current accountability is ' + (account.obligations.availability === 'UNAVAILABLE' ? 'unavailable; review it with FSMO.' : 'shown on this page.') : 'The account will regain access; any pending activation still needs completion.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={status.isPending} onClick={() => { void status.mutateAsync(account).then(value => { setNotice(value.is_active ? 'Account reactivated.' : 'Account deactivated; obligations and history preserved.'); setConfirm(false) }, () => undefined) }}>Confirm {account.is_active ? 'Deactivation' : 'Reactivation'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </> }</ManagementPage>
}
export function StaffDetail() { return <AccountDetail staff /> }
