import { useState } from 'react'
import { Link, useParams, useLocation } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog'
import { Input } from '@/components/ui/input'
import { OperationalShell } from '@/components/application/operational-shell'
import { AppButton, PageHeading, SurfaceCard, ToneBadge } from '@/components/application/visual'
import { LoadingState } from '@/components/feedback/states'
import { useAuthStore } from '@/stores/auth-store'
import { apiErrorMessage } from '@/lib/api-error'
import { accountsApi } from '../api/accounts.api'
import { useAccount, useAccountAudit, useAccountCommand } from '../hooks/use-accounts'
import type { AccountRecord } from '../types'
const profileSchema = z.object({ name: z.string().trim().min(1).max(100), course: z.string().max(128), contact_number: z.string().max(32) })
function ProfileForm({ account }: { account: AccountRecord }) {
 const form = useForm<z.infer<typeof profileSchema>>({ resolver: zodResolver(profileSchema), defaultValues: account }); const command = useAccountCommand((values: z.infer<typeof profileSchema>) => accountsApi.profile(account.id, { ...values, expected_updated_at: account.updated_at }, crypto.randomUUID()))
 return <form noValidate onSubmit={form.handleSubmit(async values => { try { await command.mutateAsync(values) } catch { form.setFocus('name') } })} aria-busy={command.isPending}><h3>Edit profile</h3>{command.error && <p role="alert">{apiErrorMessage(command.error)}</p>}{(['name', 'course', 'contact_number'] as const).filter(field => account.borrower_type || field === 'name').map(field => <div className="auth-field" key={field}><label htmlFor={`profile-${field}`}>{field === 'name' ? 'Full name' : field === 'course' ? 'Course / program' : 'Contact number'}</label><Input id={`profile-${field}`} {...form.register(field)} disabled={command.isPending} aria-invalid={!!form.formState.errors[field]} />{form.formState.errors[field] && <p role="alert" className="field-error">{form.formState.errors[field]?.message}</p>}</div>)}<AppButton disabled={command.isPending} type="submit">Save Profile</AppButton></form>
}
export function AccountDetail({ staff = false }: { staff?: boolean }) {
 const { id = '' } = useParams(); const admin = useAuthStore(s => s.user?.role === 'ADMIN'); const query = useAccount(id, staff); const [page, setPage] = useState(1); const audit = useAccountAudit(id, staff, page); const [confirm, setConfirm] = useState(false); const [notice, setNotice] = useState(''); const location = useLocation()
 const status = useAccountCommand((account: AccountRecord) => accountsApi.status(account, staff, crypto.randomUUID())); const resend = useAccountCommand(() => accountsApi.resend(id, staff, crypto.randomUUID()))
 const base = staff ? '/admin/administration/accounts' : '/staff/borrowers'; const account = query.data
 return <OperationalShell active={staff ? 'Administration' : 'Borrowers'}><PageHeading title={account?.name ?? 'Account Details'} description="Identity, status and account history." /><Link to={base}>← Back to {staff ? 'accounts' : 'borrowers'}</Link>{query.isPending ? <LoadingState label="Loading account…" /> : query.isError ? <p role="alert">{apiErrorMessage(query.error)}</p> : account && <>
 {(location.state as { created?: boolean } | null)?.created && <p role="status" className="management-notice">Account created. The account holder must complete activation.</p>}{notice && <p role="status" className="management-notice">{notice}</p>}
 <div className="management-detail-grid"><SurfaceCard className="management-card"><h2>Account information</h2><ToneBadge tone={account.is_active ? 'success' : 'neutral'}>{account.is_active ? 'Active' : 'Inactive'}</ToneBadge><dl className="management-dl"><dt>Email</dt><dd>{account.email}</dd><dt>{staff ? 'Role' : 'Borrower type'}</dt><dd>{staff ? account.role : account.borrower_type || 'Unclassified existing account'}</dd>{account.student_id && <><dt>Student ID</dt><dd>{account.student_id}</dd></>}<dt>Course / program</dt><dd>{account.course || 'Not provided'}</dd><dt>Contact number</dt><dd>{account.contact_number || 'Not provided'}</dd><dt>Activation</dt><dd>{account.activation_required ? 'Required' : 'Established'}</dd><dt>Email submission</dt><dd>{account.delivery_status}. Provider acceptance does not confirm recipient delivery.</dd></dl>
 {admin && account.role !== 'ADMIN' && <div className="management-actions"><AppButton variant="outline" onClick={() => setConfirm(true)}>{account.is_active ? 'Deactivate Account' : 'Reactivate Account'}</AppButton>{account.is_active && account.activation_required && <AppButton disabled={resend.isPending} onClick={() => { void resend.mutateAsync(undefined).then(value => setNotice(`Activation submission: ${value.delivery_status}.`), () => undefined) }}>{resend.isPending ? 'Submitting…' : 'Send Activation Link'}</AppButton>}</div>}{(status.error || resend.error) && <p role="alert" className="auth-error">{apiErrorMessage(status.error ?? resend.error)}</p>}
 {admin && !staff && <ProfileForm key={account.updated_at} account={account} />}</SurfaceCard><SurfaceCard className="management-card"><h2>{staff ? 'Administrative authority' : 'Accountability overview'}</h2>{staff ? <p>Staff account creation and status changes are Admin-only. Existing Admin accounts are read-only here.</p> : account.obligations.availability === 'UNAVAILABLE' ? <><ToneBadge tone="neutral">Accountability unavailable</ToneBadge><p>Borrowing, fines and replacement records are not available in this phase. Contact FSMO to review outstanding obligations.</p></> : <dl className="management-dl"><dt>Active borrowings</dt><dd>{account.obligations.active_borrowings ?? 'Unavailable'}</dd><dt>Overdue borrowings</dt><dd>{account.obligations.overdue_borrowings ?? 'Unavailable'}</dd><dt>Unreturned units</dt><dd>{account.obligations.unreturned_units ?? 'Unavailable'}</dd><dt>Replacement units</dt><dd>{account.obligations.replacement_units ?? 'Unavailable'}</dd><dt>Fine balance (minor units)</dt><dd>{account.obligations.fine_minor ?? 'Unavailable'}</dd></dl>}<p>Deactivation preserves history and outstanding obligations. FSMO resolves them separately.</p></SurfaceCard></div>
 {!staff && <SurfaceCard className="management-card"><h2>Borrowing history</h2><p>Borrowing history will be available when transaction management is implemented.</p></SurfaceCard>}
 {admin && <SurfaceCard className="management-card"><h2>Account audit history</h2>{audit.isPending ? <LoadingState label="Loading audit history…" /> : audit.isError ? <p role="alert">{apiErrorMessage(audit.error)}</p> : audit.data.length === 0 ? <p>No recorded management events.</p> : <ol className="management-audit">{audit.data.map(event => <li key={event.id}><strong>{event.action.replaceAll('_', ' ').toLowerCase()}</strong><time dateTime={event.occurred_at}>{new Date(event.occurred_at).toLocaleString()}</time><small>Actor: {event.actor_id}</small></li>)}</ol>}<div className="management-actions"><AppButton variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous events</AppButton><AppButton variant="outline" disabled={(audit.data?.length ?? 0) < 25} onClick={() => setPage(page + 1)}>Next events</AppButton></div></SurfaceCard>}
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{account.is_active ? 'Deactivate' : 'Reactivate'} {account.name}?</AlertDialogTitle><AlertDialogDescription>{account.is_active ? 'This account will lose access. Outstanding fines, active or overdue borrowings, unreturned equipment and replacement obligations will remain unchanged. These obligations do not block authorized deactivation. Current accountability is ' + (account.obligations.availability === 'UNAVAILABLE' ? 'unavailable; review it with FSMO.' : 'shown on this page.') : 'The account will regain access; any pending activation still needs completion.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={status.isPending} onClick={() => { void status.mutateAsync(account).then(value => { setNotice(value.is_active ? 'Account reactivated.' : 'Account deactivated; obligations and history preserved.'); setConfirm(false) }, () => undefined) }}>Confirm {account.is_active ? 'Deactivation' : 'Reactivation'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </> }</OperationalShell>
}
export function StaffDetail() { return <AccountDetail staff /> }
