import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { Download } from 'lucide-react'
import { FileDropzone } from '@/components/application/file-dropzone'
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog'
import { AppButton, ToneBadge } from '@/components/application/visual'
import { ManagementPage, ManagementCard, FormField, FormActions, Notice, WorkflowSteps } from '@/components/application/management'
import { NativeSelect } from '@/components/ui/native-select'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { DirectoryTableRegion } from '@/components/application/directory'
import { apiErrorMessage } from '@/lib/api-error'
import { accountsApi } from '../api/accounts.api'
import { useAccountCommand } from '../hooks/use-accounts'
import type { RosterBatch } from '../types'
export function StudentBulk() {
 const [operation, setOperation] = useState<'CREATE' | 'DEACTIVATE'>('CREATE'); const [file, setFile] = useState<File | null>(null); const [batch, setBatch] = useState<RosterBatch | null>(null); const [rows, setRows] = useState<number[]>([]); const [confirm, setConfirm] = useState(false); const [localError, setLocalError] = useState('')
 const prepare = useAccountCommand((input: { file: File; operation: string }) => accountsApi.prepare(input.file, input.operation)); const commit = useAccountCommand((input: { id: string; rows: number[] }) => accountsApi.confirm(input.id, input.rows)); const download = useAccountCommand(() => accountsApi.template())
 const submitting = useRef(false)
 const busy = prepare.isPending || commit.isPending; const valid = batch?.rows.filter(row => !row.error).map(row => row.number) ?? []
 async function template() { try { const blob = await download.mutateAsync(undefined); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'elabtrack-students.xlsx'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) } catch { /* rendered below */ } }
 async function preview() { if (!file || busy) return; if (file.size > 768 * 1024 || !file.name.toLowerCase().endsWith('.xlsx')) { setLocalError('Choose an .xlsx file no larger than 768 KiB.'); return } setLocalError(''); try { setBatch(await prepare.mutateAsync({ file, operation })); setRows([]) } catch { setBatch(null) } }
 return <ManagementPage title="Student Bulk Management" description="Preview a Student roster before creating or deactivating accounts." back={{to:'/staff/borrowers',label:'Back to borrowers'}} actions={<AppButton variant="outline" disabled={download.isPending} onClick={() => { void template() }}><Download aria-hidden="true" />Download Student Template</AppButton>}>
 <WorkflowSteps steps={['Download template','Upload roster','Validate & review','Confirm operation','Results']} current={batch?.confirmed?4:confirm?3:batch?2:file?1:0} />
 {(localError || prepare.error || commit.error || download.error) && <Notice tone="danger">{localError || apiErrorMessage(prepare.error ?? commit.error ?? download.error)}</Notice>}
 <ManagementCard title="Student roster" description="Students only. Faculty, Staff and Admin accounts are excluded.">
 <FormField id="bulk-operation" label="Operation"><NativeSelect value={operation} disabled={busy} onChange={e => { setOperation(e.target.value as typeof operation); setBatch(null); setRows([]) }}><option value="CREATE">Create Student Accounts</option><option value="DEACTIVATE">Deactivate Student Accounts</option></NativeSelect></FormField>
 <FileDropzone file={file} accept=".xlsx" label="Drag and drop your Excel file here" help=".xlsx · up to 500 students · 768 KiB maximum" disabled={busy} busy={prepare.isPending} onError={setLocalError} onSelect={next => { setBatch(null); setRows([]); prepare.reset(); commit.reset(); setLocalError(''); if (next && (!next.name.toLowerCase().endsWith('.xlsx') || next.size === 0 || next.size > 768 * 1024)) { setFile(null); setLocalError('Choose a nonempty .xlsx file no larger than 768 KiB.'); return } setFile(next) }} />
 <p className="management-note">Columns: studentId, name, email, course, contactNumber. The first three are required. Student IDs must be text cells. Passwords, roles and formulas are not accepted.</p><FormActions><AppButton disabled={!file || busy} onClick={() => { void preview() }}>{prepare.isPending ? 'Validating…' : 'Validate Roster'}</AppButton></FormActions></ManagementCard>
 {batch ? <ManagementCard title={batch.confirmed ? 'Operation results' : 'Validation preview'}><div className="management-status"><ToneBadge tone="success">{valid.length} valid</ToneBadge><ToneBadge tone="danger">{batch.rows.length - valid.length} invalid</ToneBadge><span>{rows.length} selected</span></div>
 {!batch.confirmed && <p className="management-note">All selected rows commit together. Conflicting changes abort the operation; review a fresh preview. Invalid and unselected rows are not changed.</p>}{operation === 'DEACTIVATE' && <Notice tone="warning">Obligations do not block deactivation. Their balances, equipment custody, history and overdue calculations remain unchanged. Accountability may be unavailable in this phase.</Notice>}{batch.confirmed && operation === 'CREATE' && <Notice tone="success">Selected accounts were created with activation pending. Open each account and send its activation link; no automatic bulk email was sent.</Notice>}{batch.confirmed && operation === 'DEACTIVATE' && <Notice tone="success">Selected Student accounts were deactivated. History and unresolved obligations remain unchanged.</Notice>}
 {!batch.confirmed && <div><AppButton variant="outline" disabled={!valid.length||busy} onClick={() => setRows(rows.length === valid.length ? [] : valid)}>{rows.length === valid.length ? 'Clear Selection' : 'Select All Valid Rows'}</AppButton></div>}
 <DirectoryTableRegion label="Student validation preview"><Table><TableHeader><TableRow>{['Select','Student','Student ID','Result'].map(label=><TableHead scope="col" key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{batch.rows.map(row=><TableRow key={row.number}><TableCell><label className="management-checkbox"><input type="checkbox" aria-label={`Select row ${row.number}`} checked={rows.includes(row.number)} disabled={!!row.error || batch.confirmed || busy} onChange={e => setRows(e.target.checked ? [...rows, row.number] : rows.filter(n => n !== row.number))} /></label></TableCell><TableCell><strong>{row.input.name}</strong><span className="management-table-copy">{row.input.email}</span></TableCell><TableCell>{row.input.student_id}</TableCell><TableCell>{row.error ? <ToneBadge tone="danger">{row.error}</ToneBadge> : row.outcome ? <span>{row.outcome.replaceAll('_', ' ').toLowerCase()}</span> : <ToneBadge tone="success">Valid</ToneBadge>}{operation === 'DEACTIVATE' && <span className="management-table-copy">Accountability: {row.obligations.availability.toLowerCase()}</span>}{row.account_id && <Link className="management-table-copy" to={`/staff/borrowers/${row.account_id}`}>Open account</Link>}</TableCell></TableRow>)}</TableBody></Table></DirectoryTableRegion>
 {!batch.confirmed && <FormActions><AppButton disabled={!rows.length || busy} onClick={() => setConfirm(true)}>Review & Confirm {operation === 'CREATE' ? 'Creation' : 'Deactivation'}</AppButton><span className="management-note">Review every selected account before continuing.</span></FormActions>}</ManagementCard> : <ManagementCard title="Validation preview"><p className="management-empty">Upload a Student roster to see every row, identity conflict and validation result before confirmation.</p></ManagementCard>}
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Confirm {operation === 'CREATE' ? 'creation' : 'deactivation'} of {rows.length} Student accounts?</AlertDialogTitle><AlertDialogDescription>{operation === 'CREATE' ? 'Only the selected valid rows will be created. No identities are overwritten. Activation remains pending until you send each account’s link.' : 'These Students will lose account access. Outstanding fines, loans, unreturned equipment and replacement obligations do not block this action and will remain unresolved. No history is deleted.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={() => { if (!batch || submitting.current || busy) return; submitting.current = true; void commit.mutateAsync({ id: batch.id, rows: [...rows] }).then(value => { setBatch(value); setConfirm(false) }, () => undefined).finally(() => { submitting.current = false }) }}>Confirm {operation === 'CREATE' ? 'Creation' : 'Deactivation'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </ManagementPage>
}
