import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Download, Upload, Check } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog'
import { OperationalShell } from '@/components/application/operational-shell'
import { AppButton, PageHeading, SurfaceCard, ToneBadge } from '@/components/application/visual'
import { DataTableShell } from '@/components/application/data-table'
import { apiErrorMessage } from '@/lib/api-error'
import { accountsApi } from '../api/accounts.api'
import { useAccountCommand } from '../hooks/use-accounts'
import type { RosterBatch } from '../types'
export function StudentBulk() {
 const [operation, setOperation] = useState<'CREATE' | 'DEACTIVATE'>('CREATE'); const [file, setFile] = useState<File | null>(null); const [batch, setBatch] = useState<RosterBatch | null>(null); const [rows, setRows] = useState<number[]>([]); const [confirm, setConfirm] = useState(false); const [localError, setLocalError] = useState('')
 const prepare = useAccountCommand((input: { file: File; operation: string }) => accountsApi.prepare(input.file, input.operation)); const commit = useAccountCommand((input: { id: string; rows: number[] }) => accountsApi.confirm(input.id, input.rows)); const download = useAccountCommand(() => accountsApi.template())
 const busy = prepare.isPending || commit.isPending; const valid = batch?.rows.filter(row => !row.error).map(row => row.number) ?? []
 async function template() { try { const blob = await download.mutateAsync(undefined); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'elabtrack-students.xlsx'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) } catch { /* rendered below */ } }
 async function preview() { if (!file || busy) return; if (file.size > 768 * 1024 || !file.name.toLowerCase().endsWith('.xlsx')) { setLocalError('Choose an .xlsx file no larger than 768 KiB.'); return } setLocalError(''); try { setBatch(await prepare.mutateAsync({ file, operation })); setRows([]) } catch { setBatch(null) } }
 return <OperationalShell active="Borrowers"><PageHeading title="Student Bulk Management" description="Preview a Student roster before creating or deactivating accounts." /><Link to="/staff/borrowers">← Back to borrowers</Link>
 <ol className="bulk-stepper" aria-label="Bulk workflow">{['Download template', 'Upload roster', 'Validate & review', 'Confirm operation'].map((step, i) => <li key={step} aria-current={i === (batch?.confirmed ? 3 : batch ? 2 : file ? 1 : 0) ? 'step' : undefined}><span>{batch?.confirmed ? <Check size={15} /> : i + 1}</span>{step}</li>)}</ol>
 <div className="bulk-layout"><SurfaceCard className="management-card"><h2>Student roster</h2><p>Students only. Faculty, Staff and Admin accounts are excluded.</p><label className="auth-field">Operation<select value={operation} disabled={busy} onChange={e => { setOperation(e.target.value as typeof operation); setBatch(null); setRows([]) }}><option value="CREATE">Bulk Create</option><option value="DEACTIVATE">Bulk Deactivate</option></select></label><AppButton variant="outline" disabled={download.isPending} onClick={() => { void template() }}><Download size={18} />Download Student Template</AppButton><div className="bulk-upload"><label htmlFor="student-roster"><Upload size={24} aria-hidden="true" />Choose Student Excel roster</label><Input id="student-roster" type="file" accept=".xlsx" disabled={busy} onChange={e => { setFile(e.target.files?.[0] ?? null); setBatch(null); setRows([]) }} /><small>.xlsx · up to 500 students · 768 KiB maximum</small></div><p className="management-note">Columns: studentId, name, email, course, contactNumber. The first three are required. Student IDs must be text cells. Passwords, roles and formulas are not accepted.</p><AppButton disabled={!file || busy} onClick={() => { void preview() }}>{prepare.isPending ? 'Validating…' : 'Validate Roster'}</AppButton></SurfaceCard>
 <div>{(localError || prepare.error || commit.error || download.error) && <p role="alert" className="auth-error">{localError || apiErrorMessage(prepare.error ?? commit.error ?? download.error)}</p>}{batch ? <><SurfaceCard className="management-card"><h2>{batch.confirmed ? 'Operation results' : 'Validation preview'}</h2><div className="management-actions"><ToneBadge tone="success">{valid.length} valid</ToneBadge><ToneBadge tone="danger">{batch.rows.length - valid.length} invalid</ToneBadge><span>{rows.length} selected</span></div>{!batch.confirmed && <p>All selected rows commit together. Conflicting changes abort the operation; review a fresh preview. Invalid and unselected rows are not changed.</p>}{operation === 'DEACTIVATE' && <p className="management-warning">Obligations do not block deactivation. Their balances, equipment custody, history and overdue calculations remain unchanged. Accountability may be unavailable in this phase.</p>}{batch.confirmed && operation === 'CREATE' && <p role="status">Selected accounts were created with activation pending. Open each account and send its activation link; no automatic bulk email was sent.</p>}{!batch.confirmed && <AppButton variant="outline" disabled={!valid.length} onClick={() => setRows(rows.length === valid.length ? [] : valid)}> {rows.length === valid.length ? 'Clear Selection' : 'Select All Valid Rows'}</AppButton>}</SurfaceCard>
 <DataTableShell label="Student validation preview"><table className="management-table"><thead><tr><th>Select</th><th>Student</th><th>Student ID</th><th>Result</th></tr></thead><tbody>{batch.rows.map(row => <tr key={row.number}><td><input type="checkbox" aria-label={`Select row ${row.number}`} checked={rows.includes(row.number)} disabled={!!row.error || batch.confirmed || busy} onChange={e => setRows(e.target.checked ? [...rows, row.number] : rows.filter(n => n !== row.number))} /></td><td><strong>{row.input.name}</strong><small>{row.input.email}</small></td><td>{row.input.student_id}</td><td>{row.error ? <ToneBadge tone="danger">{row.error}</ToneBadge> : row.outcome ? <span>{row.outcome.replaceAll('_', ' ').toLowerCase()}</span> : <ToneBadge tone="success">Valid</ToneBadge>}{operation === 'DEACTIVATE' && <small>Accountability: {row.obligations.availability.toLowerCase()}</small>}{row.account_id && <Link to={`/staff/borrowers/${row.account_id}`}>Open account</Link>}</td></tr>)}</tbody></table></DataTableShell>
 {!batch.confirmed && <div className="bulk-confirm"><p>Review every selected account before continuing.</p><AppButton disabled={!rows.length || busy} onClick={() => setConfirm(true)}>Review & Confirm {operation === 'CREATE' ? 'Creation' : 'Deactivation'}</AppButton></div>}</> : <SurfaceCard className="management-card bulk-empty"><h2>Validation preview</h2><p>Upload a Student roster to see every row, identity conflict and validation result before confirmation.</p></SurfaceCard>}</div></div>
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Confirm {operation === 'CREATE' ? 'creation' : 'deactivation'} of {rows.length} Student accounts?</AlertDialogTitle><AlertDialogDescription>{operation === 'CREATE' ? 'Only the selected valid rows will be created. No identities are overwritten. Activation remains pending until you send each account’s link.' : 'These Students will lose account access. Outstanding fines, loans, unreturned equipment and replacement obligations do not block this action and will remain unresolved. No history is deleted.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={() => { if (batch) void commit.mutateAsync({ id: batch.id, rows }).then(value => { setBatch(value); setConfirm(false) }, () => undefined) }}>Confirm {operation === 'CREATE' ? 'Creation' : 'Deactivation'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </OperationalShell>
}
