import { useEffect, useId, useRef, useState } from 'react'
import { useAuthStore } from '@/stores/auth-store'
import { Notice, FormActions } from '@/components/application/management'
import { AppButton } from '@/components/application/visual'
import { Pencil, ImagePlus, Trash2 } from 'lucide-react'
import { ApiRequestError, apiErrorMessage } from '@/lib/api-error'
import { validateImageFile } from '@/lib/image-validation'
import { profileApi, type ProfileImage } from '../api/profile.api'
import { useProfile, useProfileCommand } from '../hooks/use-profile'
import { ProfileAvatar } from './profile-avatar'
export function ProfileEditor({category}:{category?:string}={}){
 const inputId=useId(),[preview,setPreview]=useState<string|null>(null),previewURL=useRef<string|null>(null)
 function changePreview(file:File|null){if(previewURL.current)URL.revokeObjectURL(previewURL.current);previewURL.current=file?URL.createObjectURL(file):null;setPreview(previewURL.current)}

 const user=useAuthStore(s=>s.user)!,query=useProfile(user.id),[file,setFile]=useState<File|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[validating,setValidating]=useState(false),selection=useRef(0),busy=useRef(false),attempt=useRef<{meta:ProfileImage;file:File|null;key:string}|null>(null)
 useEffect(()=>()=>{if(previewURL.current)URL.revokeObjectURL(previewURL.current)},[])

 const command=useProfileCommand<{meta:ProfileImage;file:File|null;key:string},ProfileImage>(v=>v.file?profileApi.save(v.meta,v.file,v.key):profileApi.remove(v.meta,v.key))
 async function select(value:File|null){if(command.isPending)return;const ticket=++selection.current,generation=useAuthStore.getState().generation;setFile(null);changePreview(null);setError('');setNotice('');attempt.current=null;command.reset();if(!value){setValidating(false);return}setValidating(true);try{await validateImageFile(value,'profile image');if(ticket===selection.current&&generation===useAuthStore.getState().generation){setFile(value);changePreview(value)}}catch(e){if(ticket===selection.current)setError(e instanceof Error?e.message:'Choose a valid profile image.')}finally{if(ticket===selection.current)setValidating(false)}}
 async function save(remove=false){if(busy.current||!query.data||(!remove&&!file))return;busy.current=true;const chosen=remove?null:file;if(!attempt.current||attempt.current.file!==chosen)attempt.current={meta:{...query.data},file:chosen,key:crypto.randomUUID()};try{await command.mutateAsync(attempt.current);setFile(null);changePreview(null);attempt.current=null;setNotice(remove?'Profile image removed. Initials are shown.':'Profile image updated.')}catch(e){if(e instanceof ApiRequestError&&e.status===409)attempt.current=null;/* Other uncertain failures retain the same key. */}finally{busy.current=false}}
 return <section className="account-profile-header" aria-label="Profile image and identity"><div className="account-avatar-editor">{preview?<img className="profile-avatar profile-avatar-large" src={preview} alt="Selected profile image preview"/>:<ProfileAvatar id={user.id} name={user.name} className="profile-avatar-large"/>}<AppButton variant="ghost" className="avatar-edit-button" aria-label="Change Picture" disabled={command.isPending||query.isPending} onClick={()=>document.getElementById(inputId)?.click()}><Pencil aria-hidden="true"/></AppButton></div><div className="account-profile-identity"><h2>{user.name}</h2><p>{user.role==='BORROWER'?(category?(category==='STUDENT'?'Student Borrower':'Faculty Borrower'):'Borrower account'):user.role==='ADMIN'?'Admin account':'Staff account'}</p><div className="profile-image-actions"><AppButton className="compact-upload-action" variant="ghost" aria-label="Choose image" disabled={command.isPending||query.isPending} onClick={()=>document.getElementById(inputId)?.click()}><ImagePlus aria-hidden="true"/>Change Picture</AppButton><AppButton variant="ghost" disabled={!query.data?.image_id||command.isPending||validating} onClick={()=>{void save(true)}}><Trash2 aria-hidden="true"/>Remove profile image</AppButton></div></div><input id={inputId} className="sr-only" type="file" accept="image/png,image/jpeg" aria-label="Choose profile image" disabled={command.isPending||query.isPending} onChange={e=>{void select(e.target.files?.[0]??null);e.target.value=''}}/>
 <div className="profile-image-feedback">{query.error&&<Notice tone="warning">Profile image information could not be loaded.<AppButton variant="outline" onClick={()=>{void query.refetch()}}>Retry image information</AppButton></Notice>}{notice&&<Notice tone="success">{notice}</Notice>}{command.error&&<Notice tone="danger">{apiErrorMessage(command.error)} Retry the same operation if the result is uncertain.</Notice>}{error&&<Notice tone="danger">{error}</Notice>}{validating&&<p role="status">Validating image…</p>}{file&&<><p>{file.name} · Preview only until saved. PNG/JPEG, at most 512 KiB and 2048 pixels per dimension.</p><FormActions><AppButton variant="outline" disabled={command.isPending} onClick={()=>{void select(null)}}>Cancel picture change</AppButton><AppButton disabled={!query.data||command.isPending||validating} onClick={()=>{void save()}}>{command.isPending?'Saving…':'Save profile image'}</AppButton></FormActions></>}</div></section>
}
