import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth-store'
import { profileApi, type ProfileImage } from './api/profile.api'
import { ProfileEditor } from './components/profile-editor'
import { ProfileAvatar } from './components/profile-avatar'
import { validateImageFile } from '@/lib/image-validation'
let metadata:ProfileImage
function pngFile(){const file=new File(['TEST'],'fictional.png',{type:'image/png'});vi.spyOn(file,'slice').mockReturnValue({arrayBuffer:async()=>new Uint8Array([137,80,78,71,13,10,26,10]).buffer} as Blob);return file}
function mount(element=<ProfileEditor />){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={client}>{element}</QueryClientProvider>);return client}
beforeEach(()=>{metadata={account_id:'borrower',version:0,image_id:null};useAuthStore.setState({user:{id:'borrower',name:'TEST Borrower',email:'test@example.invalid',role:'BORROWER',is_active:true},isAuthenticated:true});vi.spyOn(profileApi,'metadata').mockImplementation(async()=>metadata);vi.spyOn(profileApi,'image').mockResolvedValue(new Blob(['TEST'],{type:'image/png'}));vi.stubGlobal('createImageBitmap',vi.fn().mockResolvedValue({width:32,height:32,close:vi.fn()}));vi.stubGlobal('URL',class extends URL {static createObjectURL=vi.fn(()=> 'blob:test-avatar');static revokeObjectURL=vi.fn()})})
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();useAuthStore.getState().clear()})
it('reuses one metadata query and preserves initials when there is no image',async()=>{mount();await screen.findByRole('button',{name:'Choose image'});await waitFor(()=>expect(profileApi.metadata).toHaveBeenCalledTimes(1));expect(screen.getByLabelText('TEST Borrower initials')).toHaveTextContent('TB');expect(screen.queryByRole('button',{name:'Save profile image'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Remove profile image'})).toBeDisabled()})
it('rejects unsupported profile content before upload',async()=>{const save=vi.spyOn(profileApi,'save');mount();await waitFor(()=>expect(screen.getByLabelText('Choose profile image',{selector:'input'})).toBeEnabled());fireEvent.change(screen.getByLabelText('Choose profile image',{selector:'input'}),{target:{files:[new File(['<svg/>'],'test.svg',{type:'image/svg+xml'})]}});await screen.findByRole('alert');expect(save).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'Save profile image'})).not.toBeInTheDocument();const file=pngFile();Object.defineProperty(file,'size',{value:524289});await expect(validateImageFile(file,'profile image')).rejects.toThrow('512 KiB')})
it('prevents duplicate upload and retains exact metadata/key for an uncertain retry',async()=>{let reject!:(e:Error)=>void;const save=vi.spyOn(profileApi,'save').mockImplementationOnce(()=>new Promise((_,r)=>{reject=r})).mockImplementation(async()=>{metadata={account_id:'borrower',version:1,image_id:'new-image'};return metadata});mount();await waitFor(()=>expect(screen.getByLabelText('Choose profile image',{selector:'input'})).toBeEnabled());fireEvent.change(screen.getByLabelText('Choose profile image',{selector:'input'}),{target:{files:[pngFile()]}});await waitFor(()=>expect(screen.getByRole('button',{name:'Save profile image'})).toBeEnabled());const button=screen.getByRole('button',{name:'Save profile image'});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(save).toHaveBeenCalledTimes(1));act(()=>reject(new Error('Network unavailable')));await screen.findByRole('alert');await waitFor(()=>expect(screen.getByRole('button',{name:'Save profile image'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Save profile image'}));await waitFor(()=>expect(save).toHaveBeenCalledTimes(2));expect(save.mock.calls[1]).toEqual(save.mock.calls[0]);await screen.findByText('Profile image updated.');expect(await screen.findByAltText('TEST Borrower profile image')).toBeInTheDocument()})
it('removes only the current own image and keeps initials afterward',async()=>{metadata={account_id:'borrower',version:4,image_id:'current-image'};const remove=vi.spyOn(profileApi,'remove').mockImplementation(async()=>{metadata={account_id:'borrower',version:5,image_id:null};return metadata});mount();await waitFor(()=>expect(screen.getByRole('button',{name:'Remove profile image'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Remove profile image'}));await screen.findByText('Profile image removed. Initials are shown.');expect(remove).toHaveBeenCalledWith({account_id:'borrower',version:4,image_id:'current-image'},expect.any(String));expect(screen.getByLabelText('TEST Borrower initials')).toBeInTheDocument()})
it('falls back honestly when a protected image fails to load or decode',async()=>{metadata={account_id:'borrower',version:1,image_id:'image'};mount(<ProfileAvatar id="borrower" name="TEST Borrower" />);const image=await screen.findByAltText('TEST Borrower profile image');fireEvent.error(image);expect(screen.getByLabelText('TEST Borrower initials')).toBeInTheDocument();expect(screen.queryByRole('img')).not.toBeInTheDocument()})
