import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Package, ListChecks, Clock, CalendarClock, FileCheck2, ChevronRight } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'
import { AppButton } from '@/components/application/visual'
import { ManagementPage, ManagementCard, Notice } from '@/components/application/management'
import { LoadingState } from '@/components/feedback/states'
import { RecordReference } from '@/components/application/record-reference'
import { useAuthStore } from '@/stores/auth-store'
import { apiErrorMessage } from '@/lib/api-error'
import { manilaTimeCompact } from '@/features/borrowing/lib/time'
import { pesos } from '@/features/borrowing/lib/money'
import { useDashboard } from '../hooks/use-reporting'
const colors=['#5265db','#e8a52b','#6e56cf','#d75e69']
const eventLabels:Record<string,string>={SUBMITTED:'Request submitted',CHECKED_OUT:'Equipment issued',DIRECT:'Direct issuance',RETURN:'Return recorded',REPLACEMENT:'Replacement accepted',FINE_CLEARED:'Fine resolved',DENIED:'Request denied',CANCELLED:'Request cancelled',EXPIRED:'Reservation expired',COMPLETED:'Borrowing completed'}
function OperationalDashboard(){
 const [days,setDays]=useState(7), query=useDashboard(days),data=query.data,admin=useAuthStore(s=>s.user?.role==='ADMIN'),reports=admin?'/admin/reports':'/staff/reports'
 const kpis=[['pending_requests','Pending Requests',ListChecks,'blue','/staff/requests?status=PENDING'],['active_loans','Active Borrowings',Package,'green','/staff/requests?status=CHECKED_OUT'],['due_today','Due for Return Today',CalendarClock,'amber',reports+'?kind=active&due_today=true'],['overdue_loans','Overdue',Clock,'red',reports+'?kind=overdue']] as const
 const stock=data?[['Available','available_units'],['Reserved','reserved_units'],['Checked out','checked_out_units'],['Damaged held','damaged_held_units']].map(([name,key])=>({name,value:data.metrics[key]??0})):[]
 return <ManagementPage title="Dashboard" domain="Operational overview" description="A clear view of FSMO requests, physical stock and accountability." actions={<><AppButton variant="outline" disabled={query.isFetching} onClick={()=>{void query.refetch()}}>Refresh metrics</AppButton><AppButton role="link" nativeButton={false} render={<Link to={reports}/>}>View Reports</AppButton></>}>
 {query.isPending&&<LoadingState label="Loading current metrics…"/>}{query.error&&<Notice tone="danger">{apiErrorMessage(query.error)}</Notice>}{data&&<><p className="dashboard-asof">As of {manilaTimeCompact(data.as_of)} · Asia/Manila</p><div className="operational-kpis">{kpis.map(([key,label,Icon,tone,href])=><Link key={key} to={href} className="operational-kpi" data-tone={tone}><span className="kpi-icon"><Icon aria-hidden="true"/></span><div><strong>{(data.metrics[key]===undefined?'—':data.metrics[key].toLocaleString())}</strong><span>{label}</span></div><ChevronRight aria-hidden="true"/></Link>)}</div>
 <div className="dashboard-analytics"><ManagementCard title="Request Trends" actions={<div className="range-switch" aria-label="Trend date range">{[7,30].map(v=><AppButton key={v} variant={days===v?'default':'ghost'} aria-pressed={days===v} onClick={()=>setDays(v)}>{v} days</AppButton>)}</div>}><p className="analytics-caption">Issued and denied events; currently pending requests by submission day. Manila dates.</p><div className="analytics-chart" role="img" aria-label={`Actual issued, pending and denied counts over ${days} days`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.trends??[]} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="day" tickFormatter={v=>v.slice(5)} tick={{fill:'var(--muted-foreground)',fontSize:10}}/><YAxis allowDecimals={false} width={25} tick={{fill:'var(--muted-foreground)',fontSize:10}}/><Tooltip contentStyle={{background:'var(--card)',borderColor:'var(--border)',borderRadius:10}}/><Legend/><Bar dataKey="issued" name="Issued" fill={colors[0]} radius={[3,3,0,0]} isAnimationActive={false}/><Bar dataKey="pending" name="Pending" fill={colors[1]} radius={[3,3,0,0]} isAnimationActive={false}/><Bar dataKey="denied" name="Denied" fill={colors[3]} radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><details className="chart-data"><summary>View exact daily counts</summary><table><thead><tr><th>Date</th><th>Issued</th><th>Pending</th><th>Denied</th></tr></thead><tbody>{data.trends?.map(t=><tr key={t.day}><td>{t.day}</td><td>{t.issued}</td><td>{t.pending}</td><td>{t.denied}</td></tr>)}</tbody></table></details></ManagementCard>
 <ManagementCard title="Equipment Status"><div className="stock-ring" role="img" aria-label={`Total tracked physical units: ${data.metrics.total_tracked_units}. ${stock.map(s=>`${s.name}: ${s.value}`).join(', ')}`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={stock} dataKey="value" innerRadius="65%" outerRadius="90%" stroke="var(--card)" isAnimationActive={false}>{stock.map((s,i)=><Cell key={s.name} fill={colors[i]}/>)}</Pie><Tooltip contentStyle={{background:'var(--card)',borderColor:'var(--border)'}}/></PieChart></ResponsiveContainer><div className="stock-ring-label"><strong>{data.metrics.total_tracked_units?.toLocaleString()}</strong><span>Total tracked</span></div></div><ul className="chart-legend">{stock.map((s,i)=><li key={s.name}><i style={{background:colors[i]}}/><span>{s.name}</span><strong>{s.value.toLocaleString()}</strong></li>)}</ul>{stock.every(s=>s.value===0)&&<p className="analytics-caption">No physical stock recorded.</p>}</ManagementCard>
 <ManagementCard title="Recent Activities"><div className="recent-event-list">{data.recent.map(e=><Link key={e.id} to={`/staff/requests/${e.borrowing_id}`}><span className="activity-event-icon"><FileCheck2 aria-hidden="true"/></span><div><strong>{eventLabels[e.kind]??e.kind.replaceAll('_',' ')}</strong><RecordReference value={e.reference}/><time dateTime={e.at}>{manilaTimeCompact(e.at)}</time></div><ChevronRight aria-hidden="true"/></Link>)}{!data.recent.length&&<p>No recorded activity yet.</p>}</div></ManagementCard></div>
 <details className="secondary-metrics" open><summary>Stock & Accountability</summary><div className="secondary-metric-grid">{Object.entries(data.metrics).filter(([key])=>!kpis.some(([k])=>key===k)).map(([key,value])=><div key={key}><span>{key.replaceAll('_minor','').replaceAll('_',' ')}</span><strong>{key.endsWith('_minor')?pesos(value):value.toLocaleString()}</strong></div>)}</div><p className="analytics-caption">Fine assessments continue until physical and replacement completion. Physical custody buckets sum to total tracked.</p></details></>}
 </ManagementPage>
}
export function DashboardPage(){return <OperationalDashboard/>}
