import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth-store'
import { inventoryApi } from '@/features/inventory/api/inventory.api'
import { reportingApi } from './api/reporting.api'
import { DashboardPage } from './pages/dashboard'
import { ReportsPage } from './pages/reports'
import { canVisit } from '@/features/auth/navigation'
const definition = { key: 'inventory', label: 'Inventory', columns: ['Name', 'Available'], equipment_filter: true, category_filter: true, borrower_filter: false, admin_only: false }
function mount(element: React.ReactNode, path = '/staff/reports') { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><MemoryRouter initialEntries={[path]}>{element}</MemoryRouter></QueryClientProvider>) }
beforeEach(() => { useAuthStore.setState({ user: { id: 'staff', name: 'TEST Staff', email: 'fictional@example.invalid', role: 'STAFF', is_active: true }, isAuthenticated: false }); vi.spyOn(reportingApi, 'definitions').mockResolvedValue([definition]); vi.spyOn(inventoryApi, 'categories').mockResolvedValue([{ id: 'category', name: 'Utensils', is_active: true, version: 1 }]); vi.spyOn(reportingApi, 'report').mockImplementation(async (_kind, filter) => ({ kind: 'inventory', columns: definition.columns, rows: filter.search === 'missing' ? [] : [['Spoon', '15']], total: filter.search === 'missing' ? 0 : 51, page: filter.page, per_page: filter.per_page, as_of: '2026-10-10T00:00:00Z' })) })
afterEach(() => { cleanup(); vi.restoreAllMocks(); useAuthStore.setState({ user: null }); vi.unstubAllGlobals() })
it('renders recorded metrics and preserves a legitimate zero without fake placeholders', async () => { vi.spyOn(reportingApi, 'dashboard').mockResolvedValue({ metrics: { available_units: 15, reserved_units: 0, total_tracked_units: 20, outstanding_fines_minor: 1000 }, recent: [], as_of: '2026-10-10T00:00:00Z' }); mount(<DashboardPage />); expect((await screen.findAllByText('15')).length).toBeGreaterThan(0);expect(screen.getAllByText('0').length).toBeGreaterThan(0); expect(screen.getByText('₱10.00')).toBeInTheDocument(); expect(screen.queryByText('This feature is not available yet')).not.toBeInTheDocument(); expect(screen.getByRole('link', { name: 'View Reports' })).toHaveAttribute('href', '/staff/reports') })
it('does not replace unavailable metrics with zero', async () => { vi.spyOn(reportingApi, 'dashboard').mockRejectedValue(new Error('unavailable')); mount(<DashboardPage />); await screen.findByRole('alert'); expect(screen.queryByText('Available physical units')).not.toBeInTheDocument() })
it('resets pagination when search/category changes and uses exact server totals', async () => { mount(<ReportsPage />, '/staff/reports?page=3'); await screen.findByText('Spoon'); expect(screen.getByText(/51 matching records/)).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Search report'), { target: { value: 'missing' } }); await waitFor(() => expect(reportingApi.report).toHaveBeenLastCalledWith('inventory', expect.objectContaining({ page: 1, search: 'missing' }), expect.any(AbortSignal))); expect(await screen.findByText(/0 matching records/)).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Equipment category'), { target: { value: 'category' } }); await waitFor(() => expect(reportingApi.report).toHaveBeenLastCalledWith('inventory', expect.objectContaining({ category_id: 'category' }), expect.any(AbortSignal))); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); await waitFor(() => expect(reportingApi.report).toHaveBeenLastCalledWith('inventory', expect.objectContaining({ page: 1, search: '', status: '' }), expect.any(AbortSignal))); expect(screen.queryByLabelText(/UUID|Equipment ID/)).not.toBeInTheDocument() })
it('maps inclusive Manila date controls to exclusive UTC end and exports identical filters', async () => { const exportFile = vi.spyOn(reportingApi, 'export').mockResolvedValue(new Blob(['Name,Available\r\nSpoon,15\r\n'])); vi.stubGlobal('URL', Object.assign(URL, { createObjectURL: vi.fn(() => 'blob:synthetic'), revokeObjectURL: vi.fn() })); vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined); mount(<ReportsPage />); await screen.findByText('Spoon'); fireEvent.change(screen.getByLabelText('From date (Manila)'), { target: { value: '2026-10-10' } }); fireEvent.change(screen.getByLabelText('Through date (Manila)'), { target: { value: '2026-10-12' } }); await waitFor(() => expect(reportingApi.report).toHaveBeenLastCalledWith('inventory', expect.objectContaining({ from: '2026-10-09T16:00:00.000Z', to: '2026-10-12T16:00:00.000Z' }), expect.any(AbortSignal))); await waitFor(() => expect(screen.getByRole('button', { name: 'Export Filtered CSV' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: 'Export Filtered CSV' })); await waitFor(() => expect(exportFile).toHaveBeenCalledWith('inventory', expect.objectContaining({ from: '2026-10-09T16:00:00.000Z', to: '2026-10-12T16:00:00.000Z' }))); await screen.findByText(/Filtered CSV prepared/) })
it('requires narrower filters for oversized exports', async () => { vi.mocked(reportingApi.report).mockResolvedValue({ kind: 'inventory', columns: definition.columns, rows: [['Spoon', '15']], total: 5001, page: 1, per_page: 25, as_of: '2026-10-10T00:00:00Z' }); mount(<ReportsPage />); await screen.findByText(/More than 5000 rows/); expect(screen.getByRole('button', { name: 'Export Filtered CSV' })).toBeDisabled() })
it('keeps reports in the operational route allowlist', () => { expect(canVisit('STAFF', '/staff/reports')).toBe(true); expect(canVisit('BORROWER', '/staff/reports')).toBe(false); expect(canVisit('STAFF', '/admin/reports')).toBe(false) })
it('clears the active-loan-only due-today scope when changing report kinds',async()=>{
 vi.mocked(reportingApi.definitions).mockResolvedValue([definition,{...definition,key:'active',label:'Active Borrowings'}])
 mount(<ReportsPage/>,'/staff/reports?kind=active&due_today=true')
 await waitFor(()=>expect(reportingApi.report).toHaveBeenCalledWith('active',expect.objectContaining({due_today:true}),expect.any(AbortSignal)))
 expect(screen.getByRole('button',{name:'Clear due-today scope'})).toBeInTheDocument()
 fireEvent.change(screen.getByLabelText('Report type'),{target:{value:'inventory'}})
 await waitFor(()=>{ expect(reportingApi.report).toHaveBeenLastCalledWith('inventory',expect.objectContaining({page:1}),expect.any(AbortSignal)); expect(vi.mocked(reportingApi.report).mock.lastCall?.[1]).not.toHaveProperty('due_today') })
 expect(screen.queryByRole('button',{name:'Clear due-today scope'})).not.toBeInTheDocument()
})
