import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { AccountabilityActions } from './pages/accountability-actions'
import { borrowingApi } from './api/borrowing.api'
import { useAuthStore } from '@/stores/auth-store'
import type { Borrowing } from './types'
const record: Borrowing = { id: '11111111-1111-4111-8111-111111111111', reference: 'TEST', borrower_id: 'borrower', borrower_name: 'TEST Faculty', borrower_type: 'FACULTY', student_id: '', status: 'CHECKED_OUT', entry_path: 'DIRECT', acceptance_id: 'test', created_at: '2026-10-10T00:00:00Z', expires_at: null, checked_out_at: '2026-10-10T00:00:00Z', due_at: '2026-10-10T01:00:00Z', terminal_at: null, denial_reason: '', is_overdue: true, events: [{ id: 'event', actor_id: 'staff', kind: 'DIRECT', reason: '', occurred_at: '2026-10-10T00:00:00Z' }], items: [{ id: '22222222-2222-4222-8222-222222222222', equipment_id: 'equipment', name: 'TEST Ladle', quantity: 3, reserved_quantity: 0, issued_quantity: 3, outstanding_quantity: 3 }], obligations: [{ id: '33333333-3333-4333-8333-333333333333', item_id: '22222222-2222-4222-8222-222222222222', equipment_id: 'equipment', kind: 'DAMAGED', required: 2, accepted: 1 }], fine: { assessed_minor: 2000, cleared_minor: 1000, outstanding_minor: 1000, is_final: false, as_of: '2026-10-10T02:00:00Z' } }
function mount(v = record) { return render(<QueryClientProvider client={new QueryClient()}><AccountabilityActions record={v} onSuccess={vi.fn()} /></QueryClientProvider>) }
beforeEach(() => useAuthStore.setState({ user: { id: 'staff', email: 'test@example.invalid', name: 'TEST Staff', role: 'STAFF', is_active: true } }))
afterEach(() => { cleanup(); vi.restoreAllMocks(); useAuthStore.setState({ user: null }) })
it('keeps borrowers read-only and reserves fine resolution for Admin', () => { mount(); expect(screen.queryByText('Admin Fine Resolution')).not.toBeInTheDocument(); cleanup(); useAuthStore.setState({ user: { ...useAuthStore.getState().user!, role: 'BORROWER' } }); mount(); expect(screen.queryByRole('button')).not.toBeInTheDocument() })
it('requires explanation and separate mixed return review and prevents double submission', async () => {
 let resolve!: (v: Borrowing) => void
 const request = vi.spyOn(borrowingApi, 'recordReturn').mockImplementation(() => new Promise(r => { resolve = r }))
 mount(); fireEvent.change(screen.getByLabelText('Good returned'), { target: { value: '1' } }); fireEvent.change(screen.getByLabelText('Damaged received'), { target: { value: '1' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Return' })); await screen.findByText('Record the in-person verification explanation.'); expect(request).not.toHaveBeenCalled()
 fireEvent.change(screen.getByLabelText(/Verification explanation/), { target: { value: 'Physically inspected with borrower present' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Return' })); const confirm = await screen.findByRole('button', { name: 'Confirm Reviewed Operation' }); expect(request).not.toHaveBeenCalled(); expect(screen.getByText(/Damage\/loss creates exact/)).toBeInTheDocument()
 fireEvent.click(confirm); fireEvent.click(confirm); await waitFor(() => expect(request).toHaveBeenCalledTimes(1)); expect(request).toHaveBeenCalledWith(record.id, { confirm: true, expected_event_count: 1, reason: 'Physically inspected with borrower present', lines: [{ item_id: record.items[0].id, good: 1, damaged: 1, lost: 0 }] }, expect.any(String)); resolve(record); await waitFor(() => expect(screen.getByRole('button', { name: 'Review Return' })).toBeInTheDocument())
})
it('rejects processing beyond physical outstanding before any request', async () => { const request = vi.spyOn(borrowingApi, 'recordReturn'); mount(); fireEvent.change(screen.getByLabelText('Good returned'), { target: { value: '4' } }); fireEvent.change(screen.getByLabelText(/Verification explanation/), { target: { value: 'Verified' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Return' })); await screen.findByText('Processed quantities cannot exceed the current physical outstanding.'); expect(request).not.toHaveBeenCalled() })
it('requires physical equivalence confirmation and rejects excess replacements', async () => { const request = vi.spyOn(borrowingApi, 'replace'); mount(); fireEvent.change(screen.getByLabelText(/Inspection and equivalence explanation/), { target: { value: 'Inspected' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Replacement' })); await screen.findByText('Confirm that the replacement was physically received and is equivalent.'); fireEvent.click(screen.getByRole('checkbox')); fireEvent.change(screen.getByLabelText(/Quantity received/), { target: { value: '2' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Replacement' })); await screen.findByText('Quantity exceeds the remaining replacement obligation.'); expect(request).not.toHaveBeenCalled() })
it('Admin reviews entire server balance without editable payment amount', async () => { useAuthStore.setState({ user: { ...useAuthStore.getState().user!, role: 'ADMIN' } }); const request = vi.spyOn(borrowingApi, 'clearFine').mockResolvedValue(record); mount({ ...record, status: 'COMPLETED' }); fireEvent.change(screen.getByLabelText(/Resolution method/), { target: { value: 'WAIVED' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Fine Clearance' })); const confirm = await screen.findByRole('button', { name: 'Confirm Reviewed Operation' }); expect(request).not.toHaveBeenCalled(); expect(screen.queryByRole('spinbutton')).not.toBeInTheDocument(); fireEvent.click(confirm); await waitFor(() => expect(request).toHaveBeenCalledWith(record.id, { confirm: true, method: 'WAIVED', note: '', expected_outstanding_minor: 1000 }, expect.any(String))) })
it('reviews against the complete event count rather than its bounded preview',async()=>{const request=vi.spyOn(borrowingApi,'recordReturn').mockResolvedValue(record);mount({...record,event_count:71});fireEvent.change(screen.getByLabelText('Good returned'),{target:{value:'1'}});fireEvent.change(screen.getByLabelText(/Verification explanation/),{target:{value:'Physically inspected'}});fireEvent.click(screen.getByRole('button',{name:'Review Return'}));fireEvent.click(await screen.findByRole('button',{name:'Confirm Reviewed Operation'}));await waitFor(()=>expect(request).toHaveBeenCalledWith(record.id,expect.objectContaining({expected_event_count:71}),expect.any(String)))})
