import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, useLocation } from 'react-router-dom'
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth-store'
import { inventoryApi } from '@/features/inventory/api/inventory.api'
import { borrowingApi } from './api/borrowing.api'
import { useCartStore } from './stores/cart-store'
import { RequestCompose } from './pages/request-compose'
import { BorrowingDirectory } from './pages/borrowing-directory'
import { checkoutSchema, denialSchema, selectionSchema } from './schemas/borrowing.schema'
import { manilaInstant, manilaTime } from './lib/time'
import { canVisit } from '@/features/auth/navigation'
import type { Equipment } from '@/features/inventory/types'
const equipment: Equipment = { id: '11111111-1111-4111-8111-111111111111', name: 'TEST Ladle', description: '', category_id: null, category_name: '', status: 'ACTIVE', stock: { available: 5, reserved: 0, checked_out: 0, damaged_held: 0, total_tracked: 5 }, stock_sequence: 1, metadata_version: 1, image_id: null, created_at: '', updated_at: '' }
function Location() { return <output aria-label="URL">{useLocation().pathname + useLocation().search}</output> }
function mount(component: React.ReactNode, url = '/borrower/borrowings/new') { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[url]}>{component}<Location /></MemoryRouter></QueryClientProvider>); return client }
beforeEach(() => { useCartStore.getState().clear();vi.spyOn(inventoryApi,'categories').mockResolvedValue([]); useAuthStore.setState({ user: { id: 'test-borrower', role: 'BORROWER', name: 'TEST Borrower', email: 'test@example.invalid', is_active: true } }); vi.spyOn(inventoryApi, 'list').mockResolvedValue({ items: [equipment], page: 1, per_page: 25, total: 1, totals: equipment.stock }); vi.spyOn(inventoryApi, 'detail').mockResolvedValue(equipment) })
afterEach(() => { cleanup(); vi.restoreAllMocks(); useAuthStore.setState({ user: null }) })
it('uses Manila instead of the device timezone and rejects impossible dates', () => { expect(manilaInstant('2026-10-10T12:30')).toBe('2026-10-10T04:30:00.000Z'); expect(manilaInstant('2026-02-30T12:30')).toBeUndefined(); expect(manilaInstant('invalid')).toBeUndefined(); expect(manilaTime('2026-10-10T04:30:00Z')).toContain('Manila') })
it('validates positive unique multi-item requests', () => { expect(selectionSchema.safeParse({ items: [{ equipment_id: equipment.id, quantity: 1 }] }).success).toBe(true); for (const quantity of [0, -1, 1.2, 2147483648]) expect(selectionSchema.safeParse({ items: [{ equipment_id: equipment.id, quantity }] }).success).toBe(false); expect(selectionSchema.safeParse({ items: [{ equipment_id: equipment.id, quantity: 1 }, { equipment_id: equipment.id, quantity: 2 }] }).success).toBe(false) })
it('requires explanation and explicit physical handover with future due time', () => { expect(denialSchema.safeParse({ reason: ' ' }).success).toBe(false); expect(denialSchema.safeParse({ reason: 'Operational conflict' }).success).toBe(true); expect(checkoutSchema.safeParse({ due_local: '2099-12-01T12:00', handover: false }).success).toBe(false); expect(checkoutSchema.safeParse({ due_local: '2020-01-01T12:00', handover: true }).success).toBe(false); expect(checkoutSchema.safeParse({ due_local: '2099-12-01T12:00', handover: true }).success).toBe(true) })
it('allows new own details routes but never grants borrower staff routes', () => { expect(canVisit('BORROWER', '/borrower/borrowings/new')).toBe(true); expect(canVisit('BORROWER', '/borrower/borrowings/' + equipment.id)).toBe(true); expect(canVisit('STAFF', '/borrower/borrowings/new')).toBe(false); expect(canVisit('BORROWER', '/staff/requests/' + equipment.id)).toBe(false) })
it('requires review before submission and prevents duplicate clicks', async () => {
 let finish!: (value: never) => void; const submit = vi.spyOn(borrowingApi, 'submit').mockImplementation(() => new Promise(resolve => { finish = resolve }))
 mount(<RequestCompose />); fireEvent.click(await screen.findByRole('button', { name: 'Add TEST Ladle to cart' })); fireEvent.change(await screen.findByLabelText("Cart TEST Ladle quantity"), { target: { value: '2' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Request' }));fireEvent.click(await screen.findByRole('button',{name:'Continue to Confirmation'})); await screen.findByRole('button', { name: 'Confirm Request' }); expect(submit).not.toHaveBeenCalled(); const button = screen.getByRole('button', { name: 'Confirm Request' }); fireEvent.click(button); fireEvent.click(button); await waitFor(() => expect(submit).toHaveBeenCalledTimes(1)); expect(submit).toHaveBeenCalledWith({ items: [{ equipment_id: equipment.id, quantity: 2 }], confirm: true }, expect.any(String)); finish({ id: equipment.id } as never); await waitFor(() => expect(screen.getByLabelText('URL')).toHaveTextContent('/borrower/borrowings/' + equipment.id))
})
it('uses server pagination and restores status/search filters from URL', async () => { const list = vi.spyOn(borrowingApi, 'list').mockImplementation(async filter => ({ items: [], total: 51, page: filter.page, per_page: 25 })); mount(<BorrowingDirectory />, '/borrower/borrowings?page=2&status=DENIED&search=TEST'); await waitFor(() => expect(list).toHaveBeenCalledWith({ page: 2, per_page: 25, status: 'DENIED', search: 'TEST' }, expect.any(AbortSignal))); fireEvent.change(screen.getByLabelText('Borrowing status'), { target: { value: 'PENDING' } }); await waitFor(() => expect(list).toHaveBeenLastCalledWith(expect.objectContaining({ page: 1, status: 'PENDING', search: 'TEST' }), expect.any(AbortSignal))); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); await waitFor(() => expect(list).toHaveBeenLastCalledWith(expect.objectContaining({ page: 1, status: '', search: '' }), expect.any(AbortSignal))) })
it('reuses the frozen payload and key after an uncertain submission failure', async () => { const submit = vi.spyOn(borrowingApi, 'submit').mockRejectedValueOnce(new Error('Network unavailable')).mockResolvedValue({ id: equipment.id } as never); mount(<RequestCompose />); fireEvent.click(await screen.findByRole('button', { name: 'Add TEST Ladle to cart' })); await screen.findByLabelText("Cart TEST Ladle quantity"); fireEvent.click(screen.getByRole('button', { name: 'Review Request' }));fireEvent.click(await screen.findByRole('button',{name:'Continue to Confirmation'})); fireEvent.click(await screen.findByRole('button', { name: 'Confirm Request' })); await waitFor(() => expect(submit).toHaveBeenCalledTimes(1)); await waitFor(() => expect(screen.getByRole('button', { name: 'Confirm Request' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: 'Confirm Request' })); await waitFor(() => expect(submit).toHaveBeenCalledTimes(2)); expect(submit.mock.calls[1]).toEqual(submit.mock.calls[0]) })
it('rejects a late success when the authenticated session changes', async () => { let finish!: (value: never) => void; const submit = vi.spyOn(borrowingApi, 'submit').mockImplementation(() => new Promise(resolve => { finish = resolve })); mount(<RequestCompose />); fireEvent.click(await screen.findByRole('button', { name: 'Add TEST Ladle to cart' })); await screen.findByLabelText("Cart TEST Ladle quantity"); fireEvent.click(screen.getByRole('button', { name: 'Review Request' }));fireEvent.click(await screen.findByRole('button',{name:'Continue to Confirmation'})); fireEvent.click(await screen.findByRole('button', { name: 'Confirm Request' })); await waitFor(() => expect(submit).toHaveBeenCalledTimes(1)); useAuthStore.setState({ generation: useAuthStore.getState().generation + 1 }); finish({ id: equipment.id } as never); await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('Session changed.')); expect(screen.getByLabelText('URL')).toHaveTextContent('/borrower/borrowings/new') })
