import { cleanup, fireEvent, render, screen, waitFor, act } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, useLocation } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth-store'
import { inventoryApi } from '@/features/inventory/api/inventory.api'
import { borrowingApi } from './api/borrowing.api'
import { CatalogCart } from './pages/catalog-cart'
import { useCartStore, validQuantity } from './stores/cart-store'
import type { Equipment } from '@/features/inventory/types'
import type { Borrowing } from './types'
vi.mock('@/features/notifications/components/notification-bell',()=>({NotificationBell:()=>null}))
const equipment:Equipment={id:'11111111-1111-4111-8111-111111111111',name:'TEST Ladle',description:'',category_id:null,category_name:'Utensils',status:'ACTIVE',stock:{available:5,reserved:0,checked_out:0,damaged_held:0,total_tracked:5},stock_sequence:1,metadata_version:1,image_id:null,created_at:'',updated_at:''}
const other={...equipment,id:'22222222-2222-4222-8222-222222222222',name:'TEST Pot'}
function Location(){return <output aria-label="URL">{useLocation().pathname+useLocation().search}</output>}
function mount(url='/borrower/equipment'){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[url]}><CatalogCart /><Location /></MemoryRouter></QueryClientProvider>);return client}
beforeEach(()=>{useAuthStore.setState({user:{id:'test-borrower',name:'TEST',email:'test@example.invalid',role:'BORROWER',is_active:true},isAuthenticated:true});useCartStore.getState().clear();vi.spyOn(inventoryApi,'list').mockResolvedValue({items:[equipment,other],page:1,per_page:25,total:2,totals:equipment.stock});vi.spyOn(inventoryApi,'detail').mockImplementation(async id=>id===equipment.id?equipment:other);vi.spyOn(inventoryApi,'categories').mockResolvedValue([])})
afterEach(()=>{cleanup();vi.restoreAllMocks();useAuthStore.getState().clear();useCartStore.getState().clear()})
it('keeps quantity and Add in one row and adds each equipment exactly once',async()=>{await act(async()=>{mount()});const add=await screen.findByRole('button',{name:'Add TEST Ladle to cart'});expect(add.parentElement).toBe(screen.getByLabelText('TEST Ladle quantity').parentElement);fireEvent.change(screen.getByLabelText('TEST Ladle quantity'),{target:{value:'3'}});fireEvent.click(add);expect(useCartStore.getState().lines[0].quantity).toBe('3');fireEvent.click(screen.getByRole('button',{name:'Edit TEST Ladle in cart'}));expect(useCartStore.getState().lines).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Increase Cart TEST Ladle quantity'}));expect(screen.getByLabelText('Cart TEST Ladle quantity')).toHaveValue(4);fireEvent.click(screen.getByRole('button',{name:'Remove TEST Ladle from cart'}));expect(useCartStore.getState().lines).toHaveLength(0);expect(screen.getByText('Your cart is empty')).toBeInTheDocument()})
it('retains multi-item draft across server filter and page changes',async()=>{const list=vi.mocked(inventoryApi.list).mockImplementation(async f=>({items:f.page===2?[other]:[equipment],page:f.page,per_page:25,total:26,totals:equipment.stock}));mount();fireEvent.click(await screen.findByRole('button',{name:'Add TEST Ladle to cart'}));fireEvent.click(screen.getByRole('link',{name:'Go to next page'}));fireEvent.click(await screen.findByRole('button',{name:'Add TEST Pot to cart'}));expect(useCartStore.getState().lines).toHaveLength(2);fireEvent.change(screen.getByLabelText('Search equipment'),{target:{value:'TEST'}});await waitFor(()=>expect(list).toHaveBeenLastCalledWith(expect.objectContaining({page:1,search:'TEST'}),expect.any(AbortSignal)));expect(useCartStore.getState().lines).toHaveLength(2);fireEvent.click(screen.getByRole('button',{name:'Clear filters'}));expect(useCartStore.getState().lines).toHaveLength(2)})
it('rejects invalid and excessive quantities without silently clamping them',async()=>{mount();await screen.findByRole('button',{name:'Add TEST Ladle to cart'});for(const value of ['0','-1','1.5','6']){fireEvent.change(screen.getByLabelText('TEST Ladle quantity'),{target:{value}});expect(screen.getByRole('button',{name:'Add TEST Ladle to cart'})).toBeDisabled()}fireEvent.change(screen.getByLabelText('TEST Ladle quantity'),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:'Add TEST Ladle to cart'}));fireEvent.change(screen.getByLabelText('Cart TEST Ladle quantity'),{target:{value:'6'}});expect(screen.getByRole('button',{name:'Review Request'})).toBeDisabled();expect(useCartStore.getState().lines[0].quantity).toBe('6');expect(validQuantity('1e2',100)).toBe(false)})
it('refreshes all selected quantities before review and detects stock changes',async()=>{const detail=vi.mocked(inventoryApi.detail).mockResolvedValue({...equipment,stock:{...equipment.stock,available:1},stock_sequence:2});const submit=vi.spyOn(borrowingApi,'submit');mount();fireEvent.click(await screen.findByRole('button',{name:'Add TEST Ladle to cart'}));fireEvent.change(screen.getByLabelText('Cart TEST Ladle quantity'),{target:{value:'3'}});fireEvent.click(screen.getByRole('button',{name:'Review Request'}));fireEvent.click(await screen.findByRole('button',{name:'Continue to Confirmation'}));await screen.findByRole('alert');expect(detail).toHaveBeenCalledWith(equipment.id,expect.any(AbortSignal));expect(submit).not.toHaveBeenCalled();expect(useCartStore.getState().lines[0].quantity).toBe('3');expect(useCartStore.getState().lines[0].equipment.stock.available).toBe(1);expect(useCartStore.getState().review).toBeNull()})
it('freezes review, prevents duplicate confirmations, and reuses the key after uncertain failure',async()=>{let reject!:(e:Error)=>void;const submit=vi.spyOn(borrowingApi,'submit').mockImplementationOnce(()=>new Promise((_,r)=>{reject=r})).mockResolvedValue({id:equipment.id} as Borrowing);mount();fireEvent.click(await screen.findByRole('button',{name:'Add TEST Ladle to cart'}));fireEvent.click(screen.getByRole('button',{name:'Review Request'}));expect(screen.getByLabelText('Cart TEST Ladle quantity')).toBeEnabled();fireEvent.click(await screen.findByRole('button',{name:'Continue to Confirmation'}));const confirm=await screen.findByRole('button',{name:'Confirm Request'});expect(submit).not.toHaveBeenCalled();expect(screen.queryByLabelText('Cart TEST Ladle quantity')).not.toBeInTheDocument();fireEvent.click(confirm);fireEvent.click(confirm);await waitFor(()=>expect(submit).toHaveBeenCalledTimes(1));act(()=>reject(new Error('Network unavailable')));await screen.findByRole('alert');await waitFor(()=>expect(screen.getByRole('button',{name:'Confirm Request'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Confirm Request'}));await waitFor(()=>expect(submit).toHaveBeenCalledTimes(2));expect(submit.mock.calls[1]).toEqual(submit.mock.calls[0]);await waitFor(()=>expect(screen.getByLabelText('URL')).toHaveTextContent('/borrower/borrowings/'+equipment.id));expect(useCartStore.getState().lines).toHaveLength(0)})
it('clears private draft on logout, account replacement, or role generation change, but retains it on token refresh',()=>{useCartStore.getState().add(equipment,'2');const user=useAuthStore.getState().user!;useAuthStore.getState().setSession({user,access_token:'TEST refreshed token',expires_in:300} as never);expect(useCartStore.getState().lines).toHaveLength(1);useAuthStore.getState().setUser({...user,role:'STAFF'});expect(useCartStore.getState().lines).toHaveLength(0);useAuthStore.setState({user});useCartStore.getState().add(equipment,'2');useAuthStore.setState({user:{...user,id:'other'}});expect(useCartStore.getState().lines).toHaveLength(0);useCartStore.getState().add(equipment,'2');useAuthStore.getState().clear();expect(useCartStore.getState().lines).toHaveLength(0)})
it('does not restore removed prefill after a background refetch',async()=>{const client=mount('/borrower/borrowings/new?equipment_id='+equipment.id);await waitFor(()=>expect(useCartStore.getState().lines).toHaveLength(1));fireEvent.click(screen.getByRole('button',{name:'Remove TEST Ladle from cart'}));await act(async()=>{await client.invalidateQueries({queryKey:['inventory','test-borrower','detail',equipment.id]})});expect(useCartStore.getState().lines).toHaveLength(0)})

it('rejects a late availability response after account replacement without restoring old cart contents',async()=>{let finish!:(v:Equipment)=>void;vi.mocked(inventoryApi.detail).mockImplementationOnce(()=>new Promise(r=>{finish=r}));mount();fireEvent.click(await screen.findByRole('button',{name:'Add TEST Ladle to cart'}));fireEvent.click(screen.getByRole('button',{name:'Review Request'}));fireEvent.click(await screen.findByRole('button',{name:'Continue to Confirmation'}));await waitFor(()=>expect(inventoryApi.detail).toHaveBeenCalledTimes(1));act(()=>useAuthStore.setState({user:{...useAuthStore.getState().user!,id:'different-borrower'}}));act(()=>finish(equipment));await screen.findByRole('alert');expect(useCartStore.getState().lines).toHaveLength(0);expect(useCartStore.getState().review).toBeNull()})
