import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, useLocation } from 'react-router-dom'
import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { useAuthStore } from '@/stores/auth-store'
import { inventoryApi } from '@/features/inventory/api/inventory.api'
import { accountsApi } from '@/features/accounts/api/accounts.api'
import type { AccountRecord } from '@/features/accounts/types'
import type { Equipment } from '@/features/inventory/types'
import { borrowingApi } from './api/borrowing.api'
import type { Borrowing } from './types'
import { StaffDirectIssuance } from './pages/request-compose'
vi.mock('@/features/notifications/components/notification-bell',()=>({NotificationBell:()=>null}))
const eq:Equipment={id:'11111111-1111-4111-8111-111111111111',name:'TEST Ladle',description:'',category_id:null,category_name:'Utensils',status:'ACTIVE',stock:{available:5,reserved:0,checked_out:0,damaged_held:0,total_tracked:5},stock_sequence:1,metadata_version:1,image_id:null,created_at:'',updated_at:''}
const borrower:AccountRecord={id:'22222222-2222-4222-8222-222222222222',name:'TEST Student',email:'synthetic@example.invalid',role:'BORROWER',is_active:true,borrower_type:'STUDENT',student_id:'TEST-001',course:'TEST Culinary',contact_number:'',activation_required:false,delivery_status:'',created_at:'',updated_at:'',obligations:{availability:'AVAILABLE'}}
function Location(){return <output aria-label="URL">{useLocation().pathname}</output>}
function mount(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={['/staff/requests/direct']}><StaffDirectIssuance/><Location/></MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{useAuthStore.setState({user:{id:'staff',name:'TEST Staff',email:'staff@example.invalid',role:'STAFF',is_active:true},isAuthenticated:true});vi.spyOn(accountsApi,'list').mockResolvedValue({items:[borrower],total:1,page:1,per_page:25});vi.spyOn(borrowingApi,'eligibility').mockResolvedValue({eligible:true});vi.spyOn(inventoryApi,'list').mockResolvedValue({items:[eq],total:1,page:1,per_page:25,totals:eq.stock});vi.spyOn(inventoryApi,'detail').mockResolvedValue(eq)})
afterEach(()=>{cleanup();vi.restoreAllMocks();useAuthStore.getState().clear()})
async function select(){fireEvent.click(await screen.findByRole('button',{name:'Select borrower TEST Student'}));await screen.findByRole('button',{name:'Add TEST Ladle to cart'})}
async function stage3(){await select();fireEvent.click(screen.getByRole('button',{name:'Add TEST Ladle to cart'}));fireEvent.click(screen.getByRole('button',{name:/Next: Due Date/}));fireEvent.change(screen.getByLabelText(/Due date and time \(Asia\/Manila\)/),{target:{value:'2099-12-01T12:30'}});fireEvent.click(screen.getByRole('checkbox'))}
it('shows only the active stage and retains selections when navigating Back/Next',async()=>{mount();expect(screen.queryByLabelText('Due date and time (Asia/Manila)')).not.toBeInTheDocument();await select();expect(screen.queryByLabelText('Search issuance borrower')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Add TEST Ladle to cart'}));fireEvent.change(screen.getByLabelText('Cart TEST Ladle quantity'),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:/Next: Due Date/}));expect(screen.queryByLabelText('Search equipment to request')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/Back to Equipment/}));expect(screen.getByLabelText('Cart TEST Ladle quantity')).toHaveValue(2);expect(screen.getByLabelText('TEST Ladle quantity')).toHaveValue(2);fireEvent.click(screen.getByRole('button',{name:/Back to Borrower/}));fireEvent.click(screen.getByRole('button',{name:'Next: Equipment'}));expect(screen.getByLabelText('Cart TEST Ladle quantity')).toHaveValue(2)})
it('does not progress when current terms/activation eligibility fails',async()=>{vi.mocked(borrowingApi.eligibility).mockRejectedValue(new Error('Terms acceptance required'));mount();fireEvent.click(await screen.findByRole('button',{name:'Select borrower TEST Student'}));await screen.findByRole('alert');expect(screen.getByLabelText('Search issuance borrower')).toBeInTheDocument();expect(screen.queryByLabelText('Search equipment to request')).not.toBeInTheDocument()})
it('requires physical handover, fresh availability and final review before one atomic direct command',async()=>{let finish!:(v:Borrowing)=>void;const direct=vi.spyOn(borrowingApi,'direct').mockImplementation(()=>new Promise(r=>{finish=r}));mount();await stage3();fireEvent.click(screen.getByRole('button',{name:'Review Direct Issuance'}));const confirm=await screen.findByRole('button',{name:'Confirm Direct Issuance'});expect(direct).not.toHaveBeenCalled();fireEvent.click(confirm);fireEvent.click(confirm);await waitFor(()=>expect(direct).toHaveBeenCalledTimes(1));expect(direct).toHaveBeenCalledWith({items:[{equipment_id:eq.id,quantity:1}],borrower_id:borrower.id,due_at:'2099-12-01T04:30:00.000Z',physical_handover_confirmed:true,confirm:true},expect.any(String));finish({id:eq.id} as Borrowing);await waitFor(()=>expect(screen.getByLabelText('URL')).toHaveTextContent('/staff/requests/'+eq.id))})
it('blocks stale stock at review without changing selected quantities or issuing equipment',async()=>{vi.mocked(inventoryApi.detail).mockResolvedValue({...eq,stock:{...eq.stock,available:0}});const direct=vi.spyOn(borrowingApi,'direct');mount();await stage3();fireEvent.click(screen.getByRole('button',{name:'Review Direct Issuance'}));await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Confirm Direct Issuance'})).not.toBeInTheDocument();expect(direct).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:/Back to Equipment/}));expect(screen.getByLabelText('Cart TEST Ladle quantity')).toHaveValue(1)})
