import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { StaffActions } from './pages/staff-actions'
import { borrowingApi } from './api/borrowing.api'
import type { Borrowing } from './types'
import { useAuthStore } from '@/stores/auth-store'
import { canVisit } from '@/features/auth/navigation'
const record: Borrowing = { id: '11111111-1111-4111-8111-111111111111', reference: 'TEST reference', borrower_id: '22222222-2222-4222-8222-222222222222', borrower_name: 'TEST Faculty', borrower_type: 'FACULTY', student_id: '', status: 'PENDING', entry_path: 'REQUEST', acceptance_id: 'receipt', created_at: '2026-10-09T01:00:00Z', expires_at: '2026-10-10T01:00:00Z', checked_out_at: null, due_at: null, terminal_at: null, denial_reason: '', is_overdue: false, events: [], items: [{ id: 'item', equipment_id: 'equipment', name: 'Ladle', quantity: 2, reserved_quantity: 2, issued_quantity: 0 }] }
function mount() { const callback = vi.fn(); render(<QueryClientProvider client={new QueryClient()}><MemoryRouter><StaffActions record={record} onSuccess={callback} /></MemoryRouter></QueryClientProvider>); return callback }
beforeEach(() => useAuthStore.setState({ user: { id: 'staff', email: 'test@example.invalid', name: 'TEST Staff', role: 'STAFF', is_active: true } }))
afterEach(() => { cleanup(); vi.restoreAllMocks(); useAuthStore.setState({ user: null }) })
it('does not issue without an explicit physical handover confirmation', async () => { const decide = vi.spyOn(borrowingApi, 'decide').mockResolvedValue({ ...record, status: 'CHECKED_OUT' }); mount(); fireEvent.change(screen.getByLabelText(/Due date and time/), { target: { value: '2099-12-01T12:00' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Checkout' })); await screen.findByText('Confirm physical equipment handover.'); expect(decide).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('checkbox')); fireEvent.click(screen.getByRole('button', { name: 'Review Checkout' })); await screen.findByRole('button', { name: 'Confirm Physical Checkout' }); expect(decide).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Confirm Physical Checkout' })); await waitFor(() => expect(decide).toHaveBeenCalledWith(record.id, 'approve', { confirm: true, due_at: '2099-12-01T04:00:00.000Z', physical_handover_confirmed: true }, expect.any(String))) })
it('requires a borrower-visible explanation and a separate denial review', async () => { const decide = vi.spyOn(borrowingApi, 'decide').mockResolvedValue({ ...record, status: 'DENIED' }); const callback = mount(); fireEvent.click(screen.getByRole('button', { name: 'Deny Request' })); fireEvent.click(screen.getByRole('button', { name: 'Review Denial' })); await screen.findByText('Explain the denial.'); expect(decide).not.toHaveBeenCalled(); fireEvent.change(screen.getByLabelText(/Borrower-visible denial explanation/), { target: { value: 'Operational reason' } }); fireEvent.click(screen.getByRole('button', { name: 'Review Denial' })); await screen.findByRole('button', { name: 'Confirm Denial' }); expect(decide).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Confirm Denial' })); await waitFor(() => expect(decide).toHaveBeenCalledWith(record.id, 'deny', { confirm: true, reason: 'Operational reason' }, expect.any(String))); await waitFor(() => expect(callback).toHaveBeenCalled()) })
it('allows Staff/Admin operational routes while denying Borrowers', () => { for (const role of ['STAFF', 'ADMIN'] as const) { expect(canVisit(role, '/staff/requests/direct')).toBe(true); expect(canVisit(role, '/staff/requests/' + record.id)).toBe(true) } expect(canVisit('BORROWER', '/staff/requests/direct')).toBe(false) })
