import { useMutation, useQuery } from '@tanstack/react-query'
import { ApiRequestError } from '@/lib/api-error'
import { useAuthStore } from '@/stores/auth-store'
import { reportingApi } from '../api/reporting.api'
import type { ReportFilter } from '../types'
export function useDashboard(days = 7) { const user = useAuthStore(s => s.user); return useQuery({ queryKey: ['reporting', user?.id, user?.role, 'dashboard', days], queryFn: ({ signal }) => reportingApi.dashboard(signal, days), enabled: !!user, meta: { authenticated: true }, staleTime: 10_000, refetchInterval: 30_000 }) }
export function useReportDefinitions() { const user = useAuthStore(s => s.user); return useQuery({ queryKey: ['reporting', user?.id, user?.role, 'kinds'], queryFn: ({ signal }) => reportingApi.definitions(signal), enabled: !!user && user.role !== 'BORROWER', meta: { authenticated: true }, staleTime: 60_000 }) }
export function useReport(kind: string, filter: ReportFilter, enabled: boolean) { const user = useAuthStore(s => s.user); return useQuery({ queryKey: ['reporting', user?.id, user?.role, kind, filter], queryFn: ({ signal }) => reportingApi.report(kind, filter, signal), enabled: !!user && enabled, meta: { authenticated: true }, staleTime: 10_000 }) }
export function useReportExport() { return useMutation({ mutationFn: async ({ kind, filter }: { kind: string; filter: ReportFilter }) => { const generation = useAuthStore.getState().generation; const blob = await reportingApi.export(kind, filter); if (generation !== useAuthStore.getState().generation) throw new ApiRequestError('Session changed.', 401, 'SESSION_CHANGED'); return blob }, retry: false }) }
export function useReportPDF(){return useMutation({retry:false,mutationFn:async({kind,title,filter}:{kind:string;title:string;filter:ReportFilter})=>{const generation=useAuthStore.getState().generation;const data=await reportingApi.exportData(kind,filter);if(generation!==useAuthStore.getState().generation)throw new ApiRequestError('Session changed.',401,'SESSION_CHANGED');const {reportPDF}=await import('../lib/pdf-export');const blob=await reportPDF(data,title,filter);if(generation!==useAuthStore.getState().generation)throw new ApiRequestError('Session changed.',401,'SESSION_CHANGED');return blob}})}
