import { useState } from 'react'
import { ManagementCard, Notice, FormActions } from '@/components/application/management'
import { AppButton } from '@/components/application/visual'
import { useBorrowingHistory } from '../hooks/use-borrowing'
import { manilaTime } from '../lib/time'
import { pesos } from '../lib/money'
import type { Borrowing } from '../types'
export function BorrowingHistory({record}:{record:Borrowing}){
 const [kind,setKind]=useState('events'),[page,setPage]=useState(1),query=useBorrowingHistory(record.id,kind,page,!!record.paged_history)
 if(!record.paged_history)return null
 return <ManagementCard title="Complete recorded history" description="Browse preserved events, return conditions, replacements and fine resolutions. Quantities and balances above include the complete history."><label className="grid gap-2 text-sm">History type<select className="h-11 rounded-md border bg-background px-3" value={kind} onChange={e=>{setKind(e.target.value);setPage(1)}}>{[['events','Lifecycle events'],['returns','Return dispositions'],['replacements','Replacement receipts'],['obligations','Replacement obligations'],['clearances','Admin fine resolutions']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>{query.isPending&&<p role="status">Loading recorded history…</p>}{query.error&&<Notice tone="warning">Unable to load this history page.<AppButton variant="outline" onClick={()=>{void query.refetch()}}>Retry history</AppButton></Notice>}{query.data&&<><p className="management-note">{query.data.total} records · page {page}</p>{!query.data.items.length&&<p>No records in this history.</p>}<ul className="grid gap-3">{query.data.items.map(row=><li key={String(row.id)} className="rounded-md border p-3 text-sm break-words"><p>{manilaTime(typeof row.occurred_at==='string'?row.occurred_at:null)}{typeof row.kind==='string'&&` · ${row.kind}`}{typeof row.method==='string'&&` · ${row.method.replaceAll('_',' ')}`}</p>{typeof row.item_id==='string'&&<p>{record.items.find(i=>i.id===row.item_id)?.name}</p>}{typeof row.equipment_name==='string'&&<p>{row.equipment_name}</p>}{typeof row.good==='number'&&<p>{row.good} usable · {String(row.damaged)} damaged held · {String(row.lost)} lost</p>}{typeof row.quantity==='number'&&<p>{row.quantity} equivalent usable replacements received</p>}{typeof row.required==='number'&&<p>{String(row.accepted)} of {row.required} replacements accepted</p>}{typeof row.cleared_minor==='number'&&<p>{pesos(row.cleared_minor)} cleared · assessed {pesos(Number(row.assessed_minor))}</p>}{typeof row.reason==='string'&&<p>{row.reason}</p>}{typeof row.note==='string'&&row.note&&<p>{row.note}</p>}<p className="management-note">Record {String(row.id)}{typeof row.actor_id==='string'&&` · Actor ${row.actor_id}`}</p></li>)}</ul><FormActions><AppButton variant="outline" disabled={page===1||query.isFetching} onClick={()=>setPage(p=>p-1)}>Previous history</AppButton><AppButton variant="outline" disabled={page*25>=query.data.total||query.isFetching} onClick={()=>setPage(p=>p+1)}>Next history</AppButton></FormActions></>}</ManagementCard>
}
