import { BorrowingThumbnail } from '../components/borrowing-card'
import { useRef, useState } from 'react'
import { useLocation, useParams } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth-store'
import { AppButton, BorrowingStatusBadge, ToneBadge } from '@/components/application/visual'
import { ManagementCard, Notice } from '@/components/application/management'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { DirectoryTableRegion } from '@/components/application/directory'
import { AlertDialog, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { ErrorState, LoadingState } from '@/components/feedback/states'
import { apiErrorMessage } from '@/lib/api-error'
import { borrowingApi } from '../api/borrowing.api'
import { useBorrowing, useBorrowingCommand } from '../hooks/use-borrowing'
import type { Borrowing } from '../types'
import { manilaTimeCompact as manilaTime } from '../lib/time'
import { AccountabilityActions } from './accountability-actions'
import { BorrowingHistory } from './borrowing-history'
import { AccountabilitySummary } from './accountability-summary'
import { StaffActions } from './staff-actions'
import { BorrowingFrame } from './borrowing-frame'
export function BorrowingDetail() {
 const { id = '' } = useParams(), query = useBorrowing(id), borrower = useAuthStore(s => s.user?.role === 'BORROWER'), location = useLocation(), [review, setReview] = useState<string | null>(null), busy = useRef(false)
 const [notice,setNotice] = useState('')
 const cancel = useBorrowingCommand<string, Borrowing>(key => borrowingApi.decide(id, 'cancel', { confirm: true }, key)), v = query.data, base = borrower ? '/borrower/borrowings' : '/staff/requests'
 async function confirm() { if (!review || busy.current) return; busy.current = true; try { await cancel.mutateAsync(review); setReview(null) } catch { /* Keep key and error for retry; 409 revalidates authoritative state. */ } finally { busy.current = false } }
 return <BorrowingFrame title="Borrowing Details" description="Reservation, handover and retained request history." back={{ to: base, label: 'Back to borrowings' }}>{(location.state as { borrowingNotice?: string } | null)?.borrowingNotice && <Notice tone="success">{(location.state as { borrowingNotice: string }).borrowingNotice}</Notice>}{notice && <Notice tone="success">{notice}</Notice>}{query.isPending ? <LoadingState /> : query.isError ? <ErrorState description={apiErrorMessage(query.error)} onRetry={() => { void query.refetch() }} /> : v && <div className={borrower?'borrower-detail':undefined}>
 <ManagementCard title={v.reference} actions={<BorrowingStatusBadge status={v.status} />}><p className="detail-timezone">All times Asia/Manila · Full reference shown above</p><dl className="management-dl"><dt>Borrower</dt><dd>{v.borrower_name} · {v.borrower_type}{v.student_id && ` · ${v.student_id}`}</dd><dt>Entry</dt><dd>{v.entry_path === 'DIRECT' ? 'Direct physical issuance' : 'Borrower request'}</dd><dt>Submitted / recorded</dt><dd>{manilaTime(v.created_at)}</dd><dt>Reservation expires</dt><dd>{manilaTime(v.expires_at)}</dd><dt>Physical handover</dt><dd>{manilaTime(v.checked_out_at)}</dd><dt>Due</dt><dd>{manilaTime(v.due_at)} {v.is_overdue && <ToneBadge tone="danger">Overdue</ToneBadge>}</dd></dl>{v.status === 'PENDING' && <Notice>Stock remains reserved until checkout, cancellation, denial or expiration is recorded.</Notice>}{v.status === 'DENIED' && <Notice tone="warning" title="Denial explanation">{v.denial_reason}</Notice>}{['EXPIRED', 'CANCELLED'].includes(v.status) && <Notice>Reserved quantities were released. This record is retained in your history.</Notice>}{borrower && v.status === 'PENDING' && <AppButton variant="outline" onClick={() => { cancel.reset(); setReview(crypto.randomUUID()) }}>Cancel Pending Request</AppButton>}</ManagementCard>
 <ManagementCard title="Equipment quantities">{borrower&&<div className="borrower-item-cards">{v.items.map(i=><article key={i.id} className="borrower-item-card"><div className="detail-item-identity"><BorrowingThumbnail id={i.equipment_id}/><h3>{i.name}</h3></div><dl>{[['Requested',i.quantity],['Reserved',i.reserved_quantity],['Issued',i.issued_quantity],['Good returned',i.good_quantity],['Damaged received',i.damaged_quantity],['Lost confirmed',i.lost_quantity],['Physical outstanding',i.outstanding_quantity]].map(([label,value])=><div key={String(label)} className="contents"><dt>{label}</dt><dd>{value??'Unavailable'}</dd></div>)}</dl></article>)}</div>}<div className={borrower?'borrower-desktop-table':undefined}><DirectoryTableRegion label="Borrowing equipment"><Table><TableHeader><TableRow>{['Equipment', 'Requested', 'Reserved', 'Issued', 'Good returned', 'Damaged received', 'Lost confirmed', 'Physical outstanding'].map(h => <TableHead key={h} scope="col">{h}</TableHead>)}</TableRow></TableHeader><TableBody>{v.items.map(i => <TableRow key={i.id}><TableCell>{i.name}</TableCell><TableCell>{i.quantity}</TableCell><TableCell>{i.reserved_quantity}</TableCell><TableCell>{i.issued_quantity}</TableCell><TableCell>{i.good_quantity ?? 'Unavailable'}</TableCell><TableCell>{i.damaged_quantity ?? 'Unavailable'}</TableCell><TableCell>{i.lost_quantity ?? 'Unavailable'}</TableCell><TableCell>{i.outstanding_quantity ?? 'Unavailable'}</TableCell></TableRow>)}</TableBody></Table></DirectoryTableRegion></div>{v.status === 'CHECKED_OUT' && <Notice>Issued equipment remains in checked-out custody. Contact FSMO for face-to-face return processing.</Notice>}</ManagementCard>
 <AccountabilitySummary record={v} /><BorrowingHistory key={v.id} record={v} /><AccountabilityActions record={v} onSuccess={setNotice} />
 {!borrower && v.status==='PENDING' && <StaffActions record={v} onSuccess={setNotice} />}<ManagementCard title={v.paged_history ? "Recent request & issuance history" : "Request & issuance history"}><ol className="borrowing-timeline">{v.events.map(e => <li key={e.id}><strong>{e.kind.replaceAll('_', ' ')}</strong><p className="management-note">{manilaTime(e.occurred_at)} · {e.actor_id === null ? 'System event' : 'Authenticated account action'}</p>{e.reason && <p>{e.reason}</p>}</li>)}</ol></ManagementCard>
 </div>}
 <AlertDialog open={!!review} onOpenChange={open => { if (!open && !cancel.isPending) setReview(null) }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancel pending request?</AlertDialogTitle><AlertDialogDescription>Reserved units will become available again. Your request history will be retained.</AlertDialogDescription></AlertDialogHeader>{cancel.error && <Notice tone="danger">{apiErrorMessage(cancel.error)}</Notice>}<AlertDialogFooter><AppButton variant="outline" disabled={cancel.isPending} onClick={() => setReview(null)}>Keep Request</AppButton><AppButton disabled={cancel.isPending || v?.status !== 'PENDING'} onClick={() => { void confirm() }}>{cancel.isPending ? 'Cancelling…' : 'Confirm Cancellation'}</AppButton></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </BorrowingFrame>
}
