import { useDeferredValue } from 'react'
import { Link } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth-store'
import { useDirectoryState } from '@/hooks/use-directory-state'
import { AppButton, BorrowingStatusBadge, ToneBadge } from '@/components/application/visual'
import { DirectoryPanel, DirectorySearch, DirectorySelect, DirectoryTableRegion } from '@/components/application/directory'
import { ServerPagination } from '@/components/application/server-pagination'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { apiErrorMessage } from '@/lib/api-error'
import { useBorrowings } from '../hooks/use-borrowing'
import { manilaTime } from '../lib/time'
import { BorrowingFrame } from './borrowing-frame'
export function BorrowingDirectory() {
 const borrower = useAuthStore(s => s.user?.role === 'BORROWER'), view = useDirectoryState(), page = view.page(), search = view.value('search'), deferred = useDeferredValue(search), status = view.value('status')
 const base = borrower ? '/borrower/borrowings' : '/staff/requests'
 const query = useBorrowings({ page, per_page: 25, search: deferred, status, ...(view.value('borrower_id') ? { borrower_id: view.value('borrower_id') } : {}) }), data = query.data
 return <BorrowingFrame title={borrower ? 'My Borrowings' : 'Requests & Borrowings'} description={borrower ? 'Track pending requests, issued equipment and retained history.' : 'Review reservations and record physical equipment handover.'} actions={<AppButton nativeButton={false} render={<Link to={`${base}/${borrower ? 'new' : 'direct'}`} />}>{borrower ? 'New Request' : 'Direct Issuance'}</AppButton>}><DirectoryPanel title="Borrowing directory" summary={data ? `${data.total} matching records` : 'Current requests and history'} pending={query.isPending} error={query.isError ? apiErrorMessage(query.error) : undefined} empty={!data?.items.length} onRetry={() => { void query.refetch() }} toolbar={<><DirectorySearch label="Search borrowings" placeholder={borrower ? 'Reference' : 'Reference, borrower or Student ID'} value={search} onChange={e => view.update({ search: e.target.value }, true, true)} /><DirectorySelect label="Borrowing status" value={status} onChange={e => view.update({ status: e.target.value })}><option value="">All statuses</option>{['PENDING', 'CHECKED_OUT', 'DENIED', 'CANCELLED', 'EXPIRED'].map(s => <option key={s} value={s}>{s.replace('_', ' ')}</option>)}</DirectorySelect>{(search || status) && <AppButton variant="ghost" onClick={() => view.update({ status: '', search: '' })}>Clear filters</AppButton>}</>} footer={data && <ServerPagination label="Borrowings" page={data.page} total={data.total} perPage={data.per_page} totalPages={Math.ceil(data.total / data.per_page)} count={data.items.length} pending={query.isFetching} onPage={p => view.update({ page: String(p) }, false)} />}><DirectoryTableRegion label="Borrowings table"><Table><TableHeader><TableRow><TableHead scope="col">Reference / borrower</TableHead><TableHead scope="col">Status</TableHead><TableHead scope="col">Submitted / issued</TableHead><TableHead scope="col">Expiry / due</TableHead><TableHead scope="col">Details</TableHead></TableRow></TableHeader><TableBody>{data?.items.map(v => <TableRow key={v.id}><TableCell><Link className="directory-record-name" to={`${base}/${v.id}`}>{v.reference}</Link><span className="directory-secondary">{v.borrower_name} · {v.borrower_type}</span></TableCell><TableCell><BorrowingStatusBadge status={v.status} />{v.is_overdue && <ToneBadge tone="danger">Overdue</ToneBadge>}</TableCell><TableCell>{manilaTime(v.created_at)}</TableCell><TableCell>{manilaTime(v.status === 'PENDING' ? v.expires_at : v.due_at)}</TableCell><TableCell><AppButton variant="ghost" nativeButton={false} render={<Link to={`${base}/${v.id}`} aria-label={`Open ${v.reference}`} />}>Open</AppButton></TableCell></TableRow>)}</TableBody></Table></DirectoryTableRegion></DirectoryPanel></BorrowingFrame>
}
