import { useDeferredValue, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ShoppingBag, ShoppingCart, Trash2 } from 'lucide-react'
import { Popover, PopoverTrigger, PopoverContent, PopoverTitle } from '@/components/ui/popover'
import { BorrowerShell } from '@/components/application/shells'
import { borrowerDestinations } from '@/components/application/borrower-navigation'
import { AppButton } from '@/components/application/visual'
import { ManagementPage, ManagementCard, FormActions, Notice, WorkflowSteps } from '@/components/application/management'
import { DirectorySearch, DirectorySelect } from '@/components/application/directory'
import { ServerPagination } from '@/components/application/server-pagination'
import { EmptyState, ErrorState, LoadingState } from '@/components/feedback/states'
import { useDirectoryState } from '@/hooks/use-directory-state'
import { apiErrorMessage } from '@/lib/api-error'
import { useAuthStore } from '@/stores/auth-store'
import { useCategories, useEquipment, useEquipmentDetail } from '@/features/inventory/hooks/use-inventory'
import { EquipmentImage } from '@/features/inventory/pages/equipment-image'
import { EquipmentCard } from '../components/equipment-selection-card'
import { useCartStore, validQuantity } from '../stores/cart-store'
import { QuantityControl } from '../components/quantity-control'
import { useCartReview } from '../hooks/use-cart-review'
import { useBorrowingCommand } from '../hooks/use-borrowing'
import { borrowingApi } from '../api/borrowing.api'
import type { CartReview } from '../stores/cart-store'
import type { Borrowing } from '../types'

export function CatalogCart() {
 const view = useDirectoryState(), page = view.page(), search = view.value('search'), deferred = useDeferredValue(search), category = view.value('category_id'), categoryPage = view.page('category_page'), sort = view.value('sort') === 'available' ? 'available' : 'name', available = view.value('available_only') === 'true'
 const categories = useCategories(categoryPage), query = useEquipment({ page, per_page: 25, search: deferred, category_id: category || undefined, available_only: available, sort })
 const initial = view.value('equipment_id'), initialEquipment = useEquipmentDetail(initial)
 const lines = useCartStore(s => s.lines), review = useCartStore(s => s.review), refresh = useCartStore(s => s.refresh)
 const [categoryLabel, setCategoryLabel] = useState('Selected category'), [notice,setNotice] = useState(''), titleRef = useRef<HTMLHeadingElement>(null), busy = useRef(false), prefilled = useRef(''), actor = useAuthStore(s => s.user?.id), generation = useAuthStore(s => s.generation)
 const check = useCartReview(), submit = useBorrowingCommand<CartReview, Borrowing>(v => borrowingApi.submit(v.input,v.key)), navigate = useNavigate(), mode = review ? 'confirm' : view.value('view') === 'cart' ? 'cart' : 'browse', locked = check.isPending || submit.isPending
 const units = lines.reduce((n,v) => n + (validQuantity(v.quantity,2147483647) ? Number(v.quantity) : 0),0), invalid = lines.some(v => v.equipment.status !== 'ACTIVE' || !validQuantity(v.quantity,v.equipment.stock.available))
 useEffect(() => { if (query.data) refresh(query.data.items) },[query.data,refresh])
 useEffect(() => { if (mode !== 'browse') titleRef.current?.focus() },[mode])
 useEffect(() => { const key = `${actor}:${initial}`; if (prefilled.current !== key && initialEquipment.data && initialEquipment.data.status === 'ACTIVE' && initialEquipment.data.stock.available > 0) { prefilled.current = key; useCartStore.getState().add(initialEquipment.data,'1') } },[initialEquipment.data,actor,initial])
 function show(next: string) { view.update({ view: next === 'browse' ? '' : next },false); setNotice('') }
 async function reviewCart() {
  if (busy.current || !lines.length || invalid) return
  busy.current = true
  try { await check.mutateAsync(); show('confirm') } catch { /* Keep the draft and report the authoritative refresh error. */ } finally { busy.current = false }
 }
 async function confirm() {
  if (!review || busy.current) return
  busy.current = true
  try {
   const record = await submit.mutateAsync(review)
   if (actor !== useAuthStore.getState().user?.id || generation !== useAuthStore.getState().generation) return
   useCartStore.getState().clear()
   navigate(`/borrower/borrowings/${record.id}`,{ replace:true,state:{ borrowingNotice:'Request submitted. Stock is reserved for up to 24 hours.' } })
  } catch { /* Retry retains the same reviewed command key and quantities. */ } finally { busy.current = false }
 }
 return <BorrowerShell active="Equipment" destinations={borrowerDestinations} navigationAction={<AppButton className="catalog-cart-trigger" variant="ghost" disabled={locked||!!review} aria-label={`Request cart, ${lines.length} equipment types, ${units} units`} onClick={()=>show('cart')}><ShoppingCart aria-hidden="true"/>{lines.length>0&&<span>{lines.length}</span>}</AppButton>}><ManagementPage title={mode==='browse'?'Equipment Catalog':mode==='cart'?'Review Request':'Confirm Request'} domain="Borrowing & reservations" description={mode==='browse'?'Choose equipment and add quantities to your request.':mode==='cart'?'Check quantities and remove items before confirmation.':'Review the final selection before reserving equipment.'} actions={<AppButton variant="outline" disabled={locked||!!review} onClick={() => show(mode === 'browse' ? 'cart' : 'browse')} aria-label={`Open cart, ${lines.length} equipment types, ${units} units`}><ShoppingBag size={18} aria-hidden="true" />Cart <span className="selection-count">{lines.length}</span></AppButton>}>{notice&&mode==='browse'&&<Notice tone="success">{notice}</Notice>}<WorkflowSteps steps={['Browse & select','Review request','Confirm & submit']} current={mode==='browse'?0:mode==='cart'?1:2}/><div className="selection-layout" data-view={mode}>
 <section className="selection-browser" aria-label="Equipment browsing"><ManagementCard title="Browse equipment" className="catalog-controls"><section className="directory-filters" aria-label="Equipment catalog filters"><DirectorySearch label="Search equipment" placeholder="Equipment name" value={search} onChange={e=>view.update({search:e.target.value},true,true)} /><Popover><PopoverTrigger className="catalog-filter-trigger">Filter &amp; Sort</PopoverTrigger><PopoverContent align="end" sideOffset={8} className="catalog-filter-overlay"><PopoverTitle>Filter &amp; Sort</PopoverTitle><DirectorySelect label="Category" value={category} onChange={e=>{setCategoryLabel(e.target.selectedOptions[0]?.textContent??'Selected category');view.update({category_id:e.target.value})}}><option value="">All categories</option>{category&&!categories.data?.some(c=>c.id===category)&&<option value={category}>{categoryLabel}</option>}{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}{!c.is_active?' (inactive)':''}</option>)}</DirectorySelect><DirectorySelect label="Sort" value={sort} onChange={e=>view.update({sort:e.target.value})}><option value="name">Name</option><option value="available">Available quantity</option></DirectorySelect><label className="management-checkbox"><input type="checkbox" checked={available} onChange={e=>view.update({available_only:e.target.checked?'true':''})} />Available for borrowing</label></PopoverContent></Popover>{(search||category||available||sort!=='name')&&<AppButton variant="ghost" onClick={()=>view.update({search:'',category_id:'',available_only:'',sort:''})}>Clear filters</AppButton>}</section>{categories.isError&&<ErrorState description={apiErrorMessage(categories.error)} onRetry={()=>{void categories.refetch()}} />}{(categories.data?.length===100||categoryPage>1)&&<ServerPagination label="Catalog categories" pageKey="category_page" page={categoryPage} count={categories.data?.length??0} hasNext={categories.data?.length===100} pending={categories.isFetching} onPage={p=>view.update({category_page:String(p)},false)} />}<div className="catalog-category-chips" aria-label="Equipment categories"><AppButton variant={category?'ghost':'default'} aria-pressed={!category} onClick={()=>view.update({category_id:''})}>All</AppButton>{categories.data?.map(c=><AppButton key={c.id} variant={category===c.id?'default':'ghost'} aria-pressed={category===c.id} onClick={()=>{setCategoryLabel(c.name);view.update({category_id:c.id})}}>{c.name}</AppButton>)}</div></ManagementCard>
 {initial&&initialEquipment.isError&&<Notice tone="warning">Selected equipment could not be loaded. Choose available equipment below.</Notice>}{query.isPending?<LoadingState label="Loading equipment…" />:query.isError?<ErrorState description={apiErrorMessage(query.error)} onRetry={()=>{void query.refetch()}} />:!query.data?.items.length?<ManagementCard><EmptyState title="No equipment matches" description="Try another search or category." /></ManagementCard>:<div className="selection-equipment-list">{query.data.items.map(v=><EquipmentCard key={v.id} equipment={v} selected={lines.some(i=>i.equipment.id===v.id)} selectedQuantity={lines.find(i=>i.equipment.id===v.id)?.quantity} locked={locked||!!review||lines.length>=100} onAdd={(v,q)=>{useCartStore.getState().add(v,q);setNotice(`${v.name} added to cart.`)}} onCart={()=>show('cart')} />)}</div>}
 {query.data&&!query.isError&&<ServerPagination label="Equipment types" page={query.data.page} total={query.data.total} perPage={query.data.per_page} totalPages={Math.ceil(query.data.total/query.data.per_page)} count={query.data.items.length} pending={query.isFetching} onPage={p=>view.update({page:String(p)},false)} />}</section>
 <aside className="selection-cart" aria-label={review?'Borrowing request review':'Equipment cart'}><ManagementCard className="selection-cart-card"><div className="selection-cart-heading"><div><h2 ref={titleRef} tabIndex={-1}>{review?'Confirm request':mode==='cart'?'Review request':'Your cart'}</h2><p>{lines.length} equipment {lines.length===1?'type':'types'} · {units} units</p></div><ShoppingBag aria-hidden="true" size={24} /></div><p className="management-note">Adding to cart does not reserve stock.</p>{notice&&<Notice tone="success">{notice}</Notice>}{check.error&&<Notice tone="danger">{apiErrorMessage(check.error)}</Notice>}{submit.error&&<Notice tone="danger">{apiErrorMessage(submit.error)} Retry this confirmation to safely recover an uncertain result.</Notice>}
 {!lines.length?<EmptyState title="Your cart is empty" description="Choose equipment and a quantity, then tap Add." />:<ul className="selection-cart-lines">{lines.map(v=><li key={v.equipment.id}><div className="selection-cart-identity"><EquipmentImage record={v.equipment} compact /><div><h3>{v.equipment.name}</h3><p>{v.equipment.category_name||'Uncategorized'}</p><p>{v.equipment.stock.available} currently available</p></div></div>{review?<p className="selection-reviewed-quantity">Requesting <strong>{review.input.items.find(i=>i.equipment_id===v.equipment.id)?.quantity}</strong> units</p>:<QuantityControl name={`Cart ${v.equipment.name}`} value={v.quantity} max={v.equipment.stock.available} disabled={locked} onChange={q=>{check.reset();useCartStore.getState().quantity(v.equipment.id,q)}} action={<AppButton variant="ghost" disabled={locked} aria-label={`Remove ${v.equipment.name} from cart`} onClick={()=>{check.reset();useCartStore.getState().remove(v.equipment.id)}}><Trash2 size={18} aria-hidden="true" /></AppButton>} />}{!review&&(v.equipment.status!=='ACTIVE'||!validQuantity(v.quantity,v.equipment.stock.available))&&<p className="selection-error" role="status">{v.equipment.status!=='ACTIVE'||!v.equipment.stock.available?'Unavailable. Remove this item to continue.':`Enter 1–${v.equipment.stock.available} whole units. Your selected quantity has not been changed.`}</p>}</li>)}</ul>}
 {review?<><Notice>Confirming reserves these quantities for up to 24 hours. Staff must record physical handover. Availability and eligibility are checked again by the server.</Notice><FormActions><AppButton variant="outline" disabled={locked} onClick={()=>{submit.reset();useCartStore.getState().setReview(null);show('cart')}}>Edit cart</AppButton><AppButton disabled={locked} onClick={()=>{void confirm()}}>{submit.isPending?'Submitting…':'Confirm Request'}</AppButton></FormActions></>:<>{lines.length>=100&&<Notice>You can select up to 100 equipment types per request.</Notice>}<FormActions><AppButton variant="ghost" disabled={!lines.length||locked} onClick={()=>{useCartStore.getState().clear();check.reset()}}>Clear cart</AppButton><AppButton disabled={!lines.length||invalid||locked} onClick={()=>{if(mode==='browse')show('cart');else void reviewCart()}}>{check.isPending?'Checking availability…':mode==='browse'?'Review Request':'Continue to Confirmation'}</AppButton></FormActions></>}
 <AppButton variant="outline" className="selection-mobile-back" disabled={locked||!!review} onClick={()=>show('browse')}>Continue browsing</AppButton></ManagementCard></aside></div>{mode==='browse'&&lines.length>0&&<div className="request-cart-dock"><AppButton disabled={locked} onClick={()=>show('cart')}><ShoppingBag aria-hidden="true"/><span>Request Cart · {units} units</span><span>Review</span></AppButton></div>}</ManagementPage></BorrowerShell>
}
