import { CatalogCart } from './catalog-cart'
import { useDeferredValue, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Trash2, ArrowLeft, ArrowRight, UserRound } from 'lucide-react'
import { useEquipment } from '@/features/inventory/hooks/use-inventory'
import { EquipmentImage } from '@/features/inventory/pages/equipment-image'
import { ManagementCard, FormField, FormActions, Notice, WorkflowSteps } from '@/components/application/management'
import { DirectorySearch } from '@/components/application/directory'
import { ServerPagination } from '@/components/application/server-pagination'
import { AppButton } from '@/components/application/visual'
import { Input } from '@/components/ui/input'
import { ErrorState, LoadingState } from '@/components/feedback/states'
import { ApiRequestError, apiErrorMessage } from '@/lib/api-error'
import { useAuthStore } from '@/stores/auth-store'
import { useBorrowingCommand } from '../hooks/use-borrowing'
import { borrowingApi } from '../api/borrowing.api'
import { manilaTimeCompact } from '../lib/time'
import { StaffBorrowerPicker } from './staff-borrower-picker'
import { useDirectReview, type IssuanceLine } from '../hooks/use-direct-review'
import { EquipmentCard } from '../components/equipment-selection-card'
import { QuantityControl } from '../components/quantity-control'
import { validQuantity } from '../stores/cart-store'
import type { Borrowing, RequestInput } from '../types'
import { BorrowingFrame } from './borrowing-frame'
export { CatalogCart as BorrowerRequest } from './catalog-cart'
export function StaffDirectIssuance(){const actor=useAuthStore(s=>s.user?.id),generation=useAuthStore(s=>s.generation);return <DirectWizard key={actor+':'+generation}/>}
export function RequestCompose({direct=false}:{direct?:boolean}){return direct?<DirectWizard/>:<CatalogCart/>}
type Line=IssuanceLine
function DirectWizard(){
 const [step,setStep]=useState(0),[borrower,setBorrower]=useState({id:'',name:''}),[search,setSearch]=useState(''),deferred=useDeferredValue(search),[page,setPage]=useState(1),[lines,setLines]=useState<Line[]>([]),[due,setDue]=useState(''),[handover,setHandover]=useState(false),[review,setReview]=useState<{input:RequestInput;key:string}|null>(null),[error,setError]=useState(''),[checking,setChecking]=useState(false),busy=useRef(false),navigate=useNavigate()
 const freshReview=useDirectReview()
 const query=useEquipment({page,per_page:25,search:deferred,status:'ACTIVE',available_only:true,sort:'name'}),command=useBorrowingCommand<{input:RequestInput;key:string},Borrowing>(v=>borrowingApi.direct(v.input,v.key)),invalid=!lines.length||lines.some(v=>!validQuantity(v.quantity,v.equipment.stock.available)||v.equipment.status!=='ACTIVE'),locked=checking||command.isPending,units=lines.reduce((n,v)=>n+(validQuantity(v.quantity,2147483647)?Number(v.quantity):0),0)
 async function prepare(){if(busy.current||invalid)return;busy.current=true;setChecking(true);setError('');try{const result=await freshReview.mutateAsync({borrower:borrower.id,lines,due,handover});setLines(old=>old.map(v=>({...v,equipment:result.records.find(e=>e.id===v.equipment.id)!})));if(!result.valid)throw new ApiRequestError('Availability changed. Go back and update the highlighted quantities.',409,'CART_AVAILABILITY_CHANGED');setReview(result.review);command.reset()}catch(e){setError(apiErrorMessage(e))}finally{busy.current=false;setChecking(false)}}
 async function confirm(){if(!review||busy.current)return;busy.current=true;try{const v=await command.mutateAsync(review);navigate(`/staff/requests/${v.id}`,{replace:true,state:{borrowingNotice:'Physical issuance recorded. Equipment is now in checked-out custody.'}})}catch{/* Retry retains the frozen command key. */}finally{busy.current=false}}
 const cart=<ManagementCard title="Selected Equipment" description={`${lines.length} equipment types · ${units} units. Stock changes only after confirmed issuance.`}><ul className="selection-cart-lines">{lines.map(v=><li key={v.equipment.id}><div className="selection-cart-identity"><EquipmentImage record={v.equipment} compact/><div><h3>{v.equipment.name}</h3><p>{v.equipment.stock.available} available</p></div></div><QuantityControl name={`Cart ${v.equipment.name}`} value={v.quantity} max={v.equipment.stock.available} disabled={locked} onChange={q=>setLines(old=>old.map(i=>i.equipment.id===v.equipment.id?{...i,quantity:q}:i))} action={<AppButton variant="ghost" disabled={locked} aria-label={`Remove ${v.equipment.name} from cart`} onClick={()=>setLines(old=>old.filter(i=>i.equipment.id!==v.equipment.id))}><Trash2 aria-hidden="true"/></AppButton>}/></li>)}</ul>{!lines.length&&<p>Select equipment and add quantities to continue.</p>}</ManagementCard>
 return <BorrowingFrame title="Direct Equipment Issuance" description="Select an eligible borrower, choose equipment, then confirm physical handover." back={{to:'/staff/requests',label:'Back to borrowings'}}><div className={`direct-wizard ${step === 1 ? 'is-browsing' : ''}`}><WorkflowSteps steps={['Select Borrower','Browse Equipment','Due Date & Confirm']} current={step}/>{(error||command.error)&&<Notice tone="danger">{error||apiErrorMessage(command.error)}</Notice>}
 {step===0&&<><StaffBorrowerPicker selected={borrower.id} onSelect={(id,name)=>{setBorrower({id,name});setStep(1);setError('')}}/>{borrower.id&&<FormActions><AppButton onClick={()=>setStep(1)}>Next: Equipment</AppButton></FormActions>}</>}
 {step===1&&<div className="issuance-workspace"><Notice><UserRound aria-hidden="true"/>Issuing to <strong>{borrower.name}</strong></Notice><div className="issuance-browse-layout"><section className="issuance-browser"><DirectorySearch label="Search equipment to request" placeholder="Equipment name" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/>{query.isPending?<LoadingState/>:query.error?<ErrorState description={apiErrorMessage(query.error)} onRetry={()=>{void query.refetch()}}/>:<><div className="selection-equipment-list issuance-equipment-scroll" role="region" aria-label="Issuance equipment list" tabIndex={0}>{query.data?.items.map(v=><EquipmentCard key={v.id} staff equipment={v} selected={lines.some(i=>i.equipment.id===v.id)} selectedQuantity={lines.find(i=>i.equipment.id===v.id)?.quantity} locked={locked||lines.length>=100} onAdd={(equipment,quantity)=>setLines(old=>[...old,{equipment,quantity}])} onCart={()=>(document.querySelector('.issuance-cart input') as HTMLInputElement | null)?.focus()}/>)}</div>{!query.data?.items.length&&<Notice>No equipment matches.</Notice>}{query.data&&<ServerPagination label="Request equipment" page={page} perPage={query.data.per_page} total={query.data.total} totalPages={Math.ceil(query.data.total/query.data.per_page)} count={query.data.items.length} pending={query.isFetching} onPage={setPage}/>}</>}</section><aside className="issuance-cart">{cart}</aside></div><div className="issuance-stage-footer"><FormActions><AppButton variant="outline" onClick={()=>setStep(0)}><ArrowLeft aria-hidden="true"/>Back to Borrower</AppButton><AppButton disabled={invalid} onClick={()=>{setStep(2);setReview(null);setError('')}}>Next: Due Date<ArrowRight aria-hidden="true"/></AppButton></FormActions></div></div>}
 {step===2&&<ManagementCard title={review?'Review direct issuance':'Set Due Date & Confirm'} description="Asia/Manila. This operation records actual physical handover, not a pending reservation."><div className="issuance-summary"><div><span>Borrower</span><strong>{borrower.name}</strong></div><div><span>Selected equipment</span><strong>{lines.length} types · {units} units</strong></div></div><ul className="issuance-summary-items">{lines.map(v=><li key={v.equipment.id}><EquipmentImage record={v.equipment} compact/><span>{v.equipment.name}</span><strong>× {v.quantity}</strong></li>)}</ul>{review?<><Notice>Due {manilaTimeCompact(review.input.due_at)} · Asia/Manila. Physical handover confirmed. Final availability, eligibility and due time are rechecked by the server.</Notice><FormActions><AppButton variant="outline" disabled={locked} onClick={()=>{setReview(null);command.reset()}}>Edit issuance</AppButton><AppButton disabled={locked} onClick={()=>{void confirm()}}>{command.isPending?'Recording…':'Confirm Direct Issuance'}</AppButton></FormActions></>:<form onSubmit={e=>{e.preventDefault();void prepare()}}><FormField id="direct-due" label="Due date and time (Asia/Manila)" required hint="Select a future timestamp in Manila time."><Input id="direct-due" type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} required disabled={locked}/></FormField><label className="management-checkbox"><input type="checkbox" checked={handover} onChange={e=>setHandover(e.target.checked)} disabled={locked}/>I confirm this equipment is physically being handed to the borrower.</label><FormActions><AppButton variant="outline" disabled={locked} onClick={()=>{setStep(1);setError('')}}><ArrowLeft aria-hidden="true"/>Back to Equipment</AppButton><AppButton type="submit" disabled={locked||invalid||!handover||!due}>{checking?'Checking availability…':'Review Direct Issuance'}</AppButton></FormActions></form>}</ManagementCard>}
 </div></BorrowingFrame>
}
