import { useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { ManagementCard, FormField, FormActions, Notice, WorkflowSteps } from '@/components/application/management'
import { AppButton } from '@/components/application/visual'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { apiErrorMessage } from '@/lib/api-error'
import { borrowingApi } from '../api/borrowing.api'
import { useBorrowingCommand } from '../hooks/use-borrowing'
import { checkoutSchema, denialSchema } from '../schemas/borrowing.schema'
import { manilaInstant, manilaTime } from '../lib/time'
import type { Borrowing, DecisionInput } from '../types'
export function StaffActions({ record, onSuccess }: { record: Borrowing; onSuccess: (message: string) => void }) {
 const [action, setAction] = useState<'deny' | 'approve'>('approve'), [review, setReview] = useState<{ input: DecisionInput; action: 'deny' | 'approve'; key: string } | null>(null), busy = useRef(false)
 const checkout = useForm({ resolver: zodResolver(checkoutSchema), defaultValues: { due_local: '', handover: false } }), denial = useForm({ resolver: zodResolver(denialSchema), defaultValues: { reason: '' } })
 const mutation = useBorrowingCommand<{ input: DecisionInput; action: 'deny' | 'approve'; key: string }, Borrowing>(v => borrowingApi.decide(record.id, v.action, v.input, v.key))
 async function confirm() { if (!review || busy.current) return; busy.current = true; try { const data = await mutation.mutateAsync(review); onSuccess(data.status === 'DENIED' ? 'Request denied. Reserved quantities were released.' : 'Physical handover recorded. Reserved quantities moved to checked-out custody.') } catch { /* Keep the reviewed payload/key for safe retry. */ } finally { busy.current = false } }
 return <ManagementCard title="Staff decision" description="Approval records physical equipment handover in this same operation."><WorkflowSteps steps={['Record decision', 'Review', 'Confirm']} current={review ? 1 : 0} />{mutation.error && <Notice tone="danger">{apiErrorMessage(mutation.error)}</Notice>}{review ? <><Notice tone={review.action === 'deny' ? 'warning' : 'info'} title={review.action === 'deny' ? 'Review denial' : 'Review physical checkout'}>{review.action === 'deny' ? review.input.reason : `Issue ${record.items.reduce((sum, i) => sum + i.quantity, 0)} reserved units to ${record.borrower_name}. Due ${manilaTime(review.input.due_at)}. Physical handover is confirmed.`}</Notice><FormActions><AppButton variant="outline" disabled={mutation.isPending} onClick={() => { mutation.reset(); setReview(null) }}>Edit Decision</AppButton><AppButton disabled={mutation.isPending} onClick={() => { void confirm() }}>{mutation.isPending ? 'Recording…' : review.action === 'deny' ? 'Confirm Denial' : 'Confirm Physical Checkout'}</AppButton></FormActions></> : <><FormActions><AppButton variant={action === 'approve' ? 'default' : 'outline'} onClick={() => setAction('approve')}>Physical Checkout</AppButton><AppButton variant={action === 'deny' ? 'default' : 'outline'} onClick={() => setAction('deny')}>Deny Request</AppButton></FormActions>{action === 'approve' ? <form noValidate onSubmit={checkout.handleSubmit(v => { mutation.reset(); setReview({ action: 'approve', key: crypto.randomUUID(), input: { confirm: true, due_at: manilaInstant(v.due_local), physical_handover_confirmed: v.handover } }) })}><FormField id="checkout-due" label="Due date and time (Asia/Manila)" required hint="Use Manila time. Select a future timestamp; there is no seven-day maximum." error={checkout.formState.errors.due_local?.message}><Input type="datetime-local" {...checkout.register('due_local')} /></FormField><label className="management-checkbox"><input type="checkbox" {...checkout.register('handover')} />I confirm this equipment is physically being handed to the borrower.</label>{checkout.formState.errors.handover && <Notice tone="danger">{checkout.formState.errors.handover.message}</Notice>}<Notice>Check the borrower’s accountability with FSMO before issuance. Fines and replacements are resolved separately and are not automatically cleared by checkout.</Notice><FormActions><AppButton type="submit">Review Checkout</AppButton></FormActions></form> : <form noValidate onSubmit={denial.handleSubmit(v => { mutation.reset(); setReview({ action: 'deny', key: crypto.randomUUID(), input: { confirm: true, reason: v.reason } }) })}><FormField id="deny-reason" label="Borrower-visible denial explanation" required error={denial.formState.errors.reason?.message}><Textarea maxLength={1000} {...denial.register('reason')} /></FormField><FormActions><AppButton type="submit">Review Denial</AppButton></FormActions></form>}</>}</ManagementCard>
}
